//
// EventsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class EventsAPI {

    /**
     Create an event stream for your project.
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter createEventStreamBody: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: EventStream
     */
    open class func createEventStream(projectId: String, createEventStreamBody: CreateEventStreamBody, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> EventStream {
        return try await createEventStreamWithRequestBuilder(projectId: projectId, createEventStreamBody: createEventStreamBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create an event stream for your project.
     - POST /projects/{project_id}/eventstreams
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter createEventStreamBody: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<EventStream> 
     */
    open class func createEventStreamWithRequestBuilder(projectId: String, createEventStreamBody: CreateEventStreamBody, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<EventStream> {
        var localVariablePath = "/projects/{project_id}/eventstreams"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createEventStreamBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EventStream>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Remove an event stream from a project
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter eventStreamId: (path) Event Stream ID  The ID of the event stream to be deleted, as returned when created. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteEventStream(projectId: String, eventStreamId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteEventStreamWithRequestBuilder(projectId: projectId, eventStreamId: eventStreamId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove an event stream from a project
     - DELETE /projects/{project_id}/eventstreams/{event_stream_id}
     - Remove an event stream from a project.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter eventStreamId: (path) Event Stream ID  The ID of the event stream to be deleted, as returned when created. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteEventStreamWithRequestBuilder(projectId: String, eventStreamId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/projects/{project_id}/eventstreams/{event_stream_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let eventStreamIdPreEscape = "\(APIHelper.mapValueToPathItem(eventStreamId))"
        let eventStreamIdPostEscape = eventStreamIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{event_stream_id}", with: eventStreamIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List all event streams for the project. This endpoint is not paginated.
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListEventStreams
     */
    open class func listEventStreams(projectId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> ListEventStreams {
        return try await listEventStreamsWithRequestBuilder(projectId: projectId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all event streams for the project. This endpoint is not paginated.
     - GET /projects/{project_id}/eventstreams
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListEventStreams> 
     */
    open class func listEventStreamsWithRequestBuilder(projectId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<ListEventStreams> {
        var localVariablePath = "/projects/{project_id}/eventstreams"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListEventStreams>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an event stream for a project.
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter eventStreamId: (path) Event Stream ID  The event stream&#39;s ID. 
     - parameter setEventStreamBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: EventStream
     */
    open class func setEventStream(projectId: String, eventStreamId: String, setEventStreamBody: SetEventStreamBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> EventStream {
        return try await setEventStreamWithRequestBuilder(projectId: projectId, eventStreamId: eventStreamId, setEventStreamBody: setEventStreamBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an event stream for a project.
     - PUT /projects/{project_id}/eventstreams/{event_stream_id}
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter eventStreamId: (path) Event Stream ID  The event stream&#39;s ID. 
     - parameter setEventStreamBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<EventStream> 
     */
    open class func setEventStreamWithRequestBuilder(projectId: String, eventStreamId: String, setEventStreamBody: SetEventStreamBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<EventStream> {
        var localVariablePath = "/projects/{project_id}/eventstreams/{event_stream_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let eventStreamIdPreEscape = "\(APIHelper.mapValueToPathItem(eventStreamId))"
        let eventStreamIdPostEscape = eventStreamIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{event_stream_id}", with: eventStreamIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setEventStreamBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EventStream>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
