//
// OAuth2API.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class OAuth2API {

    /**
     Accept OAuth 2.0 Consent Request
     
     - parameter consentChallenge: (query) OAuth 2.0 Consent Request Challenge 
     - parameter acceptOAuth2ConsentRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2RedirectTo
     */
    open class func acceptOAuth2ConsentRequest(consentChallenge: String, acceptOAuth2ConsentRequest: AcceptOAuth2ConsentRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2RedirectTo {
        return try await acceptOAuth2ConsentRequestWithRequestBuilder(consentChallenge: consentChallenge, acceptOAuth2ConsentRequest: acceptOAuth2ConsentRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Accept OAuth 2.0 Consent Request
     - PUT /admin/oauth2/auth/requests/consent/accept
     - When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider to authenticate the subject and then tell Ory now about it. If the subject authenticated, he/she must now be asked if the OAuth 2.0 Client which initiated the flow should be allowed to access the resources on the subject's behalf.  The consent challenge is appended to the consent provider's URL to which the subject's user-agent (browser) is redirected to. The consent provider uses that challenge to fetch information on the OAuth2 request and then tells Ory if the subject accepted or rejected the request.  This endpoint tells Ory that the subject has authorized the OAuth 2.0 client to access resources on his/her behalf. The consent provider includes additional information, such as session data for access and ID tokens, and if the consent request should be used as basis for future requests.  The response contains a redirect URL which the consent provider should redirect the user-agent to.  The default consent provider is available via the Ory Managed Account Experience. To customize the consent provider, please head over to the OAuth 2.0 documentation.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter consentChallenge: (query) OAuth 2.0 Consent Request Challenge 
     - parameter acceptOAuth2ConsentRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2RedirectTo> 
     */
    open class func acceptOAuth2ConsentRequestWithRequestBuilder(consentChallenge: String, acceptOAuth2ConsentRequest: AcceptOAuth2ConsentRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2RedirectTo> {
        let localVariablePath = "/admin/oauth2/auth/requests/consent/accept"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: acceptOAuth2ConsentRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "consent_challenge": (wrappedValue: consentChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2RedirectTo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Accept OAuth 2.0 Login Request
     
     - parameter loginChallenge: (query) OAuth 2.0 Login Request Challenge 
     - parameter acceptOAuth2LoginRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2RedirectTo
     */
    open class func acceptOAuth2LoginRequest(loginChallenge: String, acceptOAuth2LoginRequest: AcceptOAuth2LoginRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2RedirectTo {
        return try await acceptOAuth2LoginRequestWithRequestBuilder(loginChallenge: loginChallenge, acceptOAuth2LoginRequest: acceptOAuth2LoginRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Accept OAuth 2.0 Login Request
     - PUT /admin/oauth2/auth/requests/login/accept
     - When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider to authenticate the subject and then tell the Ory OAuth2 Service about it.  The authentication challenge is appended to the login provider URL to which the subject's user-agent (browser) is redirected to. The login provider uses that challenge to fetch information on the OAuth2 request and then accept or reject the requested authentication process.  This endpoint tells Ory that the subject has successfully authenticated and includes additional information such as the subject's ID and if Ory should remember the subject's subject agent for future authentication attempts by setting a cookie.  The response contains a redirect URL which the login provider should redirect the user-agent to.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter loginChallenge: (query) OAuth 2.0 Login Request Challenge 
     - parameter acceptOAuth2LoginRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2RedirectTo> 
     */
    open class func acceptOAuth2LoginRequestWithRequestBuilder(loginChallenge: String, acceptOAuth2LoginRequest: AcceptOAuth2LoginRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2RedirectTo> {
        let localVariablePath = "/admin/oauth2/auth/requests/login/accept"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: acceptOAuth2LoginRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "login_challenge": (wrappedValue: loginChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2RedirectTo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Accept OAuth 2.0 Session Logout Request
     
     - parameter logoutChallenge: (query) OAuth 2.0 Logout Request Challenge 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2RedirectTo
     */
    open class func acceptOAuth2LogoutRequest(logoutChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2RedirectTo {
        return try await acceptOAuth2LogoutRequestWithRequestBuilder(logoutChallenge: logoutChallenge, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Accept OAuth 2.0 Session Logout Request
     - PUT /admin/oauth2/auth/requests/logout/accept
     - When a user or an application requests Ory OAuth 2.0 to remove the session state of a subject, this endpoint is used to confirm that logout request.  The response contains a redirect URL which the consent provider should redirect the user-agent to.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter logoutChallenge: (query) OAuth 2.0 Logout Request Challenge 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2RedirectTo> 
     */
    open class func acceptOAuth2LogoutRequestWithRequestBuilder(logoutChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2RedirectTo> {
        let localVariablePath = "/admin/oauth2/auth/requests/logout/accept"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "logout_challenge": (wrappedValue: logoutChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2RedirectTo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Accepts a device grant user_code request
     
     - parameter deviceChallenge: (query)  
     - parameter acceptDeviceUserCodeRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2RedirectTo
     */
    open class func acceptUserCodeRequest(deviceChallenge: String, acceptDeviceUserCodeRequest: AcceptDeviceUserCodeRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2RedirectTo {
        return try await acceptUserCodeRequestWithRequestBuilder(deviceChallenge: deviceChallenge, acceptDeviceUserCodeRequest: acceptDeviceUserCodeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Accepts a device grant user_code request
     - PUT /admin/oauth2/auth/requests/device/accept
     - Accepts a device grant user_code request
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter deviceChallenge: (query)  
     - parameter acceptDeviceUserCodeRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2RedirectTo> 
     */
    open class func acceptUserCodeRequestWithRequestBuilder(deviceChallenge: String, acceptDeviceUserCodeRequest: AcceptDeviceUserCodeRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2RedirectTo> {
        let localVariablePath = "/admin/oauth2/auth/requests/device/accept"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: acceptDeviceUserCodeRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "device_challenge": (wrappedValue: deviceChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2RedirectTo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create OAuth 2.0 Client
     
     - parameter oAuth2Client: (body) OAuth 2.0 Client Request Body 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2Client
     */
    open class func createOAuth2Client(oAuth2Client: OAuth2Client, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2Client {
        return try await createOAuth2ClientWithRequestBuilder(oAuth2Client: oAuth2Client, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create OAuth 2.0 Client
     - POST /admin/clients
     - Create a new OAuth 2.0 client. If you pass `client_secret` the secret is used, otherwise a random secret is generated. The secret is echoed in the response. It is not possible to retrieve it later on.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter oAuth2Client: (body) OAuth 2.0 Client Request Body 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2Client> 
     */
    open class func createOAuth2ClientWithRequestBuilder(oAuth2Client: OAuth2Client, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2Client> {
        let localVariablePath = "/admin/clients"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: oAuth2Client, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2Client>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete OAuth 2.0 Client
     
     - parameter id: (path) The id of the OAuth 2.0 Client. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteOAuth2Client(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteOAuth2ClientWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete OAuth 2.0 Client
     - DELETE /admin/clients/{id}
     - Delete an existing OAuth 2.0 Client by its ID.  OAuth 2.0 clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.  Make sure that this endpoint is well protected and only callable by first-party components.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) The id of the OAuth 2.0 Client. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteOAuth2ClientWithRequestBuilder(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/admin/clients/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete OAuth 2.0 Access Tokens from specific OAuth 2.0 Client
     
     - parameter clientId: (query) OAuth 2.0 Client ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteOAuth2Token(clientId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteOAuth2TokenWithRequestBuilder(clientId: clientId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete OAuth 2.0 Access Tokens from specific OAuth 2.0 Client
     - DELETE /admin/oauth2/tokens
     - This endpoint deletes OAuth2 access tokens issued to an OAuth 2.0 Client from the database.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter clientId: (query) OAuth 2.0 Client ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteOAuth2TokenWithRequestBuilder(clientId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/admin/oauth2/tokens"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "client_id": (wrappedValue: clientId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete Trusted OAuth2 JWT Bearer Grant Type Issuer
     
     - parameter id: (path) The id of the desired grant 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteTrustedOAuth2JwtGrantIssuer(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteTrustedOAuth2JwtGrantIssuerWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete Trusted OAuth2 JWT Bearer Grant Type Issuer
     - DELETE /admin/trust/grants/jwt-bearer/issuers/{id}
     - Use this endpoint to delete trusted JWT Bearer Grant Type Issuer. The ID is the one returned when you created the trust relationship.  Once deleted, the associated issuer will no longer be able to perform the JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grant.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) The id of the desired grant 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteTrustedOAuth2JwtGrantIssuerWithRequestBuilder(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/admin/trust/grants/jwt-bearer/issuers/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get an OAuth 2.0 Client
     
     - parameter id: (path) The id of the OAuth 2.0 Client. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2Client
     */
    open class func getOAuth2Client(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2Client {
        return try await getOAuth2ClientWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get an OAuth 2.0 Client
     - GET /admin/clients/{id}
     - Get an OAuth 2.0 client by its ID. This endpoint never returns the client secret.  OAuth 2.0 clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) The id of the OAuth 2.0 Client. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2Client> 
     */
    open class func getOAuth2ClientWithRequestBuilder(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2Client> {
        var localVariablePath = "/admin/clients/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2Client>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get OAuth 2.0 Consent Request
     
     - parameter consentChallenge: (query) OAuth 2.0 Consent Request Challenge 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2ConsentRequest
     */
    open class func getOAuth2ConsentRequest(consentChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2ConsentRequest {
        return try await getOAuth2ConsentRequestWithRequestBuilder(consentChallenge: consentChallenge, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get OAuth 2.0 Consent Request
     - GET /admin/oauth2/auth/requests/consent
     - When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider to authenticate the subject and then tell Ory now about it. If the subject authenticated, he/she must now be asked if the OAuth 2.0 Client which initiated the flow should be allowed to access the resources on the subject's behalf.  The consent challenge is appended to the consent provider's URL to which the subject's user-agent (browser) is redirected to. The consent provider uses that challenge to fetch information on the OAuth2 request and then tells Ory if the subject accepted or rejected the request.  The default consent provider is available via the Ory Managed Account Experience. To customize the consent provider, please head over to the OAuth 2.0 documentation.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter consentChallenge: (query) OAuth 2.0 Consent Request Challenge 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2ConsentRequest> 
     */
    open class func getOAuth2ConsentRequestWithRequestBuilder(consentChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2ConsentRequest> {
        let localVariablePath = "/admin/oauth2/auth/requests/consent"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "consent_challenge": (wrappedValue: consentChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2ConsentRequest>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get OAuth 2.0 Login Request
     
     - parameter loginChallenge: (query) OAuth 2.0 Login Request Challenge 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2LoginRequest
     */
    open class func getOAuth2LoginRequest(loginChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2LoginRequest {
        return try await getOAuth2LoginRequestWithRequestBuilder(loginChallenge: loginChallenge, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get OAuth 2.0 Login Request
     - GET /admin/oauth2/auth/requests/login
     - When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider to authenticate the subject and then tell the Ory OAuth2 Service about it.  Per default, the login provider is Ory itself. You may use a different login provider which needs to be a web-app you write and host, and it must be able to authenticate (\"show the subject a login screen\") a subject (in OAuth2 the proper name for subject is \"resource owner\").  The authentication challenge is appended to the login provider URL to which the subject's user-agent (browser) is redirected to. The login provider uses that challenge to fetch information on the OAuth2 request and then accept or reject the requested authentication process.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter loginChallenge: (query) OAuth 2.0 Login Request Challenge 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2LoginRequest> 
     */
    open class func getOAuth2LoginRequestWithRequestBuilder(loginChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2LoginRequest> {
        let localVariablePath = "/admin/oauth2/auth/requests/login"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "login_challenge": (wrappedValue: loginChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2LoginRequest>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get OAuth 2.0 Session Logout Request
     
     - parameter logoutChallenge: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2LogoutRequest
     */
    open class func getOAuth2LogoutRequest(logoutChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2LogoutRequest {
        return try await getOAuth2LogoutRequestWithRequestBuilder(logoutChallenge: logoutChallenge, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get OAuth 2.0 Session Logout Request
     - GET /admin/oauth2/auth/requests/logout
     - Use this endpoint to fetch an Ory OAuth 2.0 logout request.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter logoutChallenge: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2LogoutRequest> 
     */
    open class func getOAuth2LogoutRequestWithRequestBuilder(logoutChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2LogoutRequest> {
        let localVariablePath = "/admin/oauth2/auth/requests/logout"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "logout_challenge": (wrappedValue: logoutChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2LogoutRequest>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get Trusted OAuth2 JWT Bearer Grant Type Issuer
     
     - parameter id: (path) The id of the desired grant 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TrustedOAuth2JwtGrantIssuer
     */
    open class func getTrustedOAuth2JwtGrantIssuer(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> TrustedOAuth2JwtGrantIssuer {
        return try await getTrustedOAuth2JwtGrantIssuerWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Trusted OAuth2 JWT Bearer Grant Type Issuer
     - GET /admin/trust/grants/jwt-bearer/issuers/{id}
     - Use this endpoint to get a trusted JWT Bearer Grant Type Issuer. The ID is the one returned when you created the trust relationship.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) The id of the desired grant 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TrustedOAuth2JwtGrantIssuer> 
     */
    open class func getTrustedOAuth2JwtGrantIssuerWithRequestBuilder(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<TrustedOAuth2JwtGrantIssuer> {
        var localVariablePath = "/admin/trust/grants/jwt-bearer/issuers/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TrustedOAuth2JwtGrantIssuer>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Introspect OAuth2 Access and Refresh Tokens
     
     - parameter token: (form) The string value of the token. For access tokens, this is the \\\&quot;access_token\\\&quot; value returned from the token endpoint defined in OAuth 2.0. For refresh tokens, this is the \\\&quot;refresh_token\\\&quot; value returned. 
     - parameter scope: (form) An optional, space separated list of required scopes. If the access token was not granted one of the scopes, the result of active will be false. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: IntrospectedOAuth2Token
     */
    open class func introspectOAuth2Token(token: String, scope: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> IntrospectedOAuth2Token {
        return try await introspectOAuth2TokenWithRequestBuilder(token: token, scope: scope, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Introspect OAuth2 Access and Refresh Tokens
     - POST /admin/oauth2/introspect
     - The introspection endpoint allows to check if a token (both refresh and access) is active or not. An active token is neither expired nor revoked. If a token is active, additional information on the token will be included. You can set additional data for a token by setting `session.access_token` during the consent flow.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter token: (form) The string value of the token. For access tokens, this is the \\\&quot;access_token\\\&quot; value returned from the token endpoint defined in OAuth 2.0. For refresh tokens, this is the \\\&quot;refresh_token\\\&quot; value returned. 
     - parameter scope: (form) An optional, space separated list of required scopes. If the access token was not granted one of the scopes, the result of active will be false. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<IntrospectedOAuth2Token> 
     */
    open class func introspectOAuth2TokenWithRequestBuilder(token: String, scope: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<IntrospectedOAuth2Token> {
        let localVariablePath = "/admin/oauth2/introspect"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "scope": scope?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "token": token.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntrospectedOAuth2Token>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List OAuth 2.0 Clients
     
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter clientName: (query) The name of the clients to filter by. (optional)
     - parameter owner: (query) The owner of the clients to filter by. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [OAuth2Client]
     */
    open class func listOAuth2Clients(pageSize: Int64? = nil, pageToken: String? = nil, clientName: String? = nil, owner: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [OAuth2Client] {
        return try await listOAuth2ClientsWithRequestBuilder(pageSize: pageSize, pageToken: pageToken, clientName: clientName, owner: owner, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List OAuth 2.0 Clients
     - GET /admin/clients
     - This endpoint lists all clients in the database, and never returns client secrets. As a default it lists the first 100 clients.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter clientName: (query) The name of the clients to filter by. (optional)
     - parameter owner: (query) The owner of the clients to filter by. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[OAuth2Client]> 
     */
    open class func listOAuth2ClientsWithRequestBuilder(pageSize: Int64? = nil, pageToken: String? = nil, clientName: String? = nil, owner: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[OAuth2Client]> {
        let localVariablePath = "/admin/clients"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_token": (wrappedValue: pageToken?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "client_name": (wrappedValue: clientName?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "owner": (wrappedValue: owner?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[OAuth2Client]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List OAuth 2.0 Consent Sessions of a Subject
     
     - parameter subject: (query) The subject to list the consent sessions for. 
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to "1")
     - parameter loginSessionId: (query) The login session id to list the consent sessions for. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [OAuth2ConsentSession]
     */
    open class func listOAuth2ConsentSessions(subject: String, pageSize: Int64? = nil, pageToken: String? = nil, loginSessionId: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [OAuth2ConsentSession] {
        return try await listOAuth2ConsentSessionsWithRequestBuilder(subject: subject, pageSize: pageSize, pageToken: pageToken, loginSessionId: loginSessionId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List OAuth 2.0 Consent Sessions of a Subject
     - GET /admin/oauth2/auth/sessions/consent
     - This endpoint lists all subject's granted consent sessions, including client and granted scope. If the subject is unknown or has not granted any consent sessions yet, the endpoint returns an empty JSON array with status code 200 OK.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter subject: (query) The subject to list the consent sessions for. 
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to "1")
     - parameter loginSessionId: (query) The login session id to list the consent sessions for. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[OAuth2ConsentSession]> 
     */
    open class func listOAuth2ConsentSessionsWithRequestBuilder(subject: String, pageSize: Int64? = nil, pageToken: String? = nil, loginSessionId: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[OAuth2ConsentSession]> {
        let localVariablePath = "/admin/oauth2/auth/sessions/consent"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_token": (wrappedValue: pageToken?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject": (wrappedValue: subject.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "login_session_id": (wrappedValue: loginSessionId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[OAuth2ConsentSession]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List Trusted OAuth2 JWT Bearer Grant Type Issuers
     
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter issuer: (query) If optional \&quot;issuer\&quot; is supplied, only jwt-bearer grants with this issuer will be returned. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [TrustedOAuth2JwtGrantIssuer]
     */
    open class func listTrustedOAuth2JwtGrantIssuers(pageSize: Int64? = nil, pageToken: String? = nil, issuer: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [TrustedOAuth2JwtGrantIssuer] {
        return try await listTrustedOAuth2JwtGrantIssuersWithRequestBuilder(pageSize: pageSize, pageToken: pageToken, issuer: issuer, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Trusted OAuth2 JWT Bearer Grant Type Issuers
     - GET /admin/trust/grants/jwt-bearer/issuers
     - Use this endpoint to list all trusted JWT Bearer Grant Type Issuers.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter issuer: (query) If optional \&quot;issuer\&quot; is supplied, only jwt-bearer grants with this issuer will be returned. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[TrustedOAuth2JwtGrantIssuer]> 
     */
    open class func listTrustedOAuth2JwtGrantIssuersWithRequestBuilder(pageSize: Int64? = nil, pageToken: String? = nil, issuer: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[TrustedOAuth2JwtGrantIssuer]> {
        let localVariablePath = "/admin/trust/grants/jwt-bearer/issuers"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_token": (wrappedValue: pageToken?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "issuer": (wrappedValue: issuer?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[TrustedOAuth2JwtGrantIssuer]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     OAuth 2.0 Authorize Endpoint
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ErrorOAuth2
     */
    open class func oAuth2Authorize(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> ErrorOAuth2 {
        return try await oAuth2AuthorizeWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     OAuth 2.0 Authorize Endpoint
     - GET /oauth2/auth
     - Use open source libraries to perform OAuth 2.0 and OpenID Connect available for any programming language. You can find a list of libraries at https://oauth.net/code/  This endpoint should not be used via the Ory SDK and is only included for technical reasons. Instead, use one of the libraries linked above.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ErrorOAuth2> 
     */
    open class func oAuth2AuthorizeWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<ErrorOAuth2> {
        let localVariablePath = "/oauth2/auth"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ErrorOAuth2>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     The OAuth 2.0 Device Authorize Endpoint
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeviceAuthorization
     */
    open class func oAuth2DeviceFlow(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> DeviceAuthorization {
        return try await oAuth2DeviceFlowWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     The OAuth 2.0 Device Authorize Endpoint
     - POST /oauth2/device/auth
     - This endpoint is not documented here because you should never use your own implementation to perform OAuth2 flows. OAuth2 is a very popular protocol and a library for your programming language will exist.  To learn more about this flow please refer to the specification: https://tools.ietf.org/html/rfc8628
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeviceAuthorization> 
     */
    open class func oAuth2DeviceFlowWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<DeviceAuthorization> {
        let localVariablePath = "/oauth2/device/auth"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeviceAuthorization>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     The OAuth 2.0 Token Endpoint
     
     - parameter grantType: (form)  
     - parameter clientId: (form)  (optional)
     - parameter code: (form)  (optional)
     - parameter redirectUri: (form)  (optional)
     - parameter refreshToken: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2TokenExchange
     */
    open class func oauth2TokenExchange(grantType: String, clientId: String? = nil, code: String? = nil, redirectUri: String? = nil, refreshToken: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2TokenExchange {
        return try await oauth2TokenExchangeWithRequestBuilder(grantType: grantType, clientId: clientId, code: code, redirectUri: redirectUri, refreshToken: refreshToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     The OAuth 2.0 Token Endpoint
     - POST /oauth2/token
     - Use open source libraries to perform OAuth 2.0 and OpenID Connect available for any programming language. You can find a list of libraries here https://oauth.net/code/  This endpoint should not be used via the Ory SDK and is only included for technical reasons. Instead, use one of the libraries linked above.
     - BASIC:
       - type: http
       - name: basic
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter grantType: (form)  
     - parameter clientId: (form)  (optional)
     - parameter code: (form)  (optional)
     - parameter redirectUri: (form)  (optional)
     - parameter refreshToken: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2TokenExchange> 
     */
    open class func oauth2TokenExchangeWithRequestBuilder(grantType: String, clientId: String? = nil, code: String? = nil, redirectUri: String? = nil, refreshToken: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2TokenExchange> {
        let localVariablePath = "/oauth2/token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "client_id": clientId?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "code": code?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "grant_type": grantType.asParameter(codableHelper: apiConfiguration.codableHelper),
            "redirect_uri": redirectUri?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "refresh_token": refreshToken?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2TokenExchange>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Patch OAuth 2.0 Client
     
     - parameter id: (path) The id of the OAuth 2.0 Client. 
     - parameter jsonPatch: (body) OAuth 2.0 Client JSON Patch Body 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2Client
     */
    open class func patchOAuth2Client(id: String, jsonPatch: [JsonPatch], apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2Client {
        return try await patchOAuth2ClientWithRequestBuilder(id: id, jsonPatch: jsonPatch, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Patch OAuth 2.0 Client
     - PATCH /admin/clients/{id}
     - Patch an existing OAuth 2.0 Client using JSON Patch. If you pass `client_secret` the secret will be updated and returned via the API. This is the only time you will be able to retrieve the client secret, so write it down and keep it safe.  OAuth 2.0 clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) The id of the OAuth 2.0 Client. 
     - parameter jsonPatch: (body) OAuth 2.0 Client JSON Patch Body 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2Client> 
     */
    open class func patchOAuth2ClientWithRequestBuilder(id: String, jsonPatch: [JsonPatch], apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2Client> {
        var localVariablePath = "/admin/clients/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: jsonPatch, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2Client>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     OAuth 2.0 Device Verification Endpoint
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ErrorOAuth2
     */
    open class func performOAuth2DeviceVerificationFlow(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> ErrorOAuth2 {
        return try await performOAuth2DeviceVerificationFlowWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     OAuth 2.0 Device Verification Endpoint
     - GET /oauth2/device/verify
     - This is the device user verification endpoint. The user is redirected here when trying to log in using the device flow.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ErrorOAuth2> 
     */
    open class func performOAuth2DeviceVerificationFlowWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<ErrorOAuth2> {
        let localVariablePath = "/oauth2/device/verify"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ErrorOAuth2>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Reject OAuth 2.0 Consent Request
     
     - parameter consentChallenge: (query) OAuth 2.0 Consent Request Challenge 
     - parameter rejectOAuth2Request: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2RedirectTo
     */
    open class func rejectOAuth2ConsentRequest(consentChallenge: String, rejectOAuth2Request: RejectOAuth2Request? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2RedirectTo {
        return try await rejectOAuth2ConsentRequestWithRequestBuilder(consentChallenge: consentChallenge, rejectOAuth2Request: rejectOAuth2Request, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject OAuth 2.0 Consent Request
     - PUT /admin/oauth2/auth/requests/consent/reject
     - When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider to authenticate the subject and then tell Ory now about it. If the subject authenticated, he/she must now be asked if the OAuth 2.0 Client which initiated the flow should be allowed to access the resources on the subject's behalf.  The consent challenge is appended to the consent provider's URL to which the subject's user-agent (browser) is redirected to. The consent provider uses that challenge to fetch information on the OAuth2 request and then tells Ory if the subject accepted or rejected the request.  This endpoint tells Ory that the subject has not authorized the OAuth 2.0 client to access resources on his/her behalf. The consent provider must include a reason why the consent was not granted.  The response contains a redirect URL which the consent provider should redirect the user-agent to.  The default consent provider is available via the Ory Managed Account Experience. To customize the consent provider, please head over to the OAuth 2.0 documentation.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter consentChallenge: (query) OAuth 2.0 Consent Request Challenge 
     - parameter rejectOAuth2Request: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2RedirectTo> 
     */
    open class func rejectOAuth2ConsentRequestWithRequestBuilder(consentChallenge: String, rejectOAuth2Request: RejectOAuth2Request? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2RedirectTo> {
        let localVariablePath = "/admin/oauth2/auth/requests/consent/reject"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rejectOAuth2Request, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "consent_challenge": (wrappedValue: consentChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2RedirectTo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Reject OAuth 2.0 Login Request
     
     - parameter loginChallenge: (query) OAuth 2.0 Login Request Challenge 
     - parameter rejectOAuth2Request: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2RedirectTo
     */
    open class func rejectOAuth2LoginRequest(loginChallenge: String, rejectOAuth2Request: RejectOAuth2Request? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2RedirectTo {
        return try await rejectOAuth2LoginRequestWithRequestBuilder(loginChallenge: loginChallenge, rejectOAuth2Request: rejectOAuth2Request, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject OAuth 2.0 Login Request
     - PUT /admin/oauth2/auth/requests/login/reject
     - When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider to authenticate the subject and then tell the Ory OAuth2 Service about it.  The authentication challenge is appended to the login provider URL to which the subject's user-agent (browser) is redirected to. The login provider uses that challenge to fetch information on the OAuth2 request and then accept or reject the requested authentication process.  This endpoint tells Ory that the subject has not authenticated and includes a reason why the authentication was denied.  The response contains a redirect URL which the login provider should redirect the user-agent to.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter loginChallenge: (query) OAuth 2.0 Login Request Challenge 
     - parameter rejectOAuth2Request: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2RedirectTo> 
     */
    open class func rejectOAuth2LoginRequestWithRequestBuilder(loginChallenge: String, rejectOAuth2Request: RejectOAuth2Request? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2RedirectTo> {
        let localVariablePath = "/admin/oauth2/auth/requests/login/reject"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rejectOAuth2Request, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "login_challenge": (wrappedValue: loginChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2RedirectTo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Reject OAuth 2.0 Session Logout Request
     
     - parameter logoutChallenge: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func rejectOAuth2LogoutRequest(logoutChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await rejectOAuth2LogoutRequestWithRequestBuilder(logoutChallenge: logoutChallenge, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Reject OAuth 2.0 Session Logout Request
     - PUT /admin/oauth2/auth/requests/logout/reject
     - When a user or an application requests Ory OAuth 2.0 to remove the session state of a subject, this endpoint is used to deny that logout request. No HTTP request body is required.  The response is empty as the logout provider has to chose what action to perform next.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter logoutChallenge: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func rejectOAuth2LogoutRequestWithRequestBuilder(logoutChallenge: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/admin/oauth2/auth/requests/logout/reject"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "logout_challenge": (wrappedValue: logoutChallenge.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke OAuth 2.0 Consent Sessions of a Subject
     
     - parameter subject: (query) OAuth 2.0 Consent Subject  The subject whose consent sessions should be deleted. (optional)
     - parameter client: (query) OAuth 2.0 Client ID  If set, deletes only those consent sessions that have been granted to the specified OAuth 2.0 Client ID. (optional)
     - parameter consentRequestId: (query) Consent Request ID  If set, revoke all token chains derived from this particular consent request ID. (optional)
     - parameter all: (query) Revoke All Consent Sessions  If set to &#x60;true&#x60; deletes all consent sessions by the Subject that have been granted. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func revokeOAuth2ConsentSessions(subject: String? = nil, client: String? = nil, consentRequestId: String? = nil, all: Bool? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await revokeOAuth2ConsentSessionsWithRequestBuilder(subject: subject, client: client, consentRequestId: consentRequestId, all: all, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke OAuth 2.0 Consent Sessions of a Subject
     - DELETE /admin/oauth2/auth/sessions/consent
     - This endpoint revokes a subject's granted consent sessions and invalidates all associated OAuth 2.0 Access Tokens. You may also only revoke sessions for a specific OAuth 2.0 Client ID.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter subject: (query) OAuth 2.0 Consent Subject  The subject whose consent sessions should be deleted. (optional)
     - parameter client: (query) OAuth 2.0 Client ID  If set, deletes only those consent sessions that have been granted to the specified OAuth 2.0 Client ID. (optional)
     - parameter consentRequestId: (query) Consent Request ID  If set, revoke all token chains derived from this particular consent request ID. (optional)
     - parameter all: (query) Revoke All Consent Sessions  If set to &#x60;true&#x60; deletes all consent sessions by the Subject that have been granted. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func revokeOAuth2ConsentSessionsWithRequestBuilder(subject: String? = nil, client: String? = nil, consentRequestId: String? = nil, all: Bool? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/admin/oauth2/auth/sessions/consent"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "subject": (wrappedValue: subject?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "client": (wrappedValue: client?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "consent_request_id": (wrappedValue: consentRequestId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "all": (wrappedValue: all?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Revokes OAuth 2.0 Login Sessions by either a Subject or a SessionID
     
     - parameter subject: (query) OAuth 2.0 Subject  The subject to revoke authentication sessions for. (optional)
     - parameter sid: (query) Login Session ID  The login session to revoke. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func revokeOAuth2LoginSessions(subject: String? = nil, sid: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await revokeOAuth2LoginSessionsWithRequestBuilder(subject: subject, sid: sid, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revokes OAuth 2.0 Login Sessions by either a Subject or a SessionID
     - DELETE /admin/oauth2/auth/sessions/login
     - This endpoint invalidates authentication sessions. After revoking the authentication session(s), the subject has to re-authenticate at the Ory OAuth2 Provider. This endpoint does not invalidate any tokens.  If you send the subject in a query param, all authentication sessions that belong to that subject are revoked. No OpenID Connect Front- or Back-channel logout is performed in this case.  Alternatively, you can send a SessionID via `sid` query param, in which case, only the session that is connected to that SessionID is revoked. OpenID Connect Back-channel logout is performed in this case.  When using Ory for the identity provider, the login provider will also invalidate the session cookie.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter subject: (query) OAuth 2.0 Subject  The subject to revoke authentication sessions for. (optional)
     - parameter sid: (query) Login Session ID  The login session to revoke. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func revokeOAuth2LoginSessionsWithRequestBuilder(subject: String? = nil, sid: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/admin/oauth2/auth/sessions/login"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "subject": (wrappedValue: subject?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sid": (wrappedValue: sid?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke OAuth 2.0 Access or Refresh Token
     
     - parameter token: (form)  
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func revokeOAuth2Token(token: String, clientId: String? = nil, clientSecret: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await revokeOAuth2TokenWithRequestBuilder(token: token, clientId: clientId, clientSecret: clientSecret, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke OAuth 2.0 Access or Refresh Token
     - POST /oauth2/revoke
     - Revoking a token (both access and refresh) means that the tokens will be invalid. A revoked access token can no longer be used to make access requests, and a revoked refresh token can no longer be used to refresh an access token. Revoking a refresh token also invalidates the access token that was created with it. A token may only be revoked by the client the token was generated for.
     - BASIC:
       - type: http
       - name: basic
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter token: (form)  
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func revokeOAuth2TokenWithRequestBuilder(token: String, clientId: String? = nil, clientSecret: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/oauth2/revoke"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "client_id": clientId?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "client_secret": clientSecret?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "token": token.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Set OAuth 2.0 Client
     
     - parameter id: (path) OAuth 2.0 Client ID 
     - parameter oAuth2Client: (body) OAuth 2.0 Client Request Body 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2Client
     */
    open class func setOAuth2Client(id: String, oAuth2Client: OAuth2Client, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2Client {
        return try await setOAuth2ClientWithRequestBuilder(id: id, oAuth2Client: oAuth2Client, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Set OAuth 2.0 Client
     - PUT /admin/clients/{id}
     - Replaces an existing OAuth 2.0 Client with the payload you send. If you pass `client_secret` the secret is used, otherwise the existing secret is used.  If set, the secret is echoed in the response. It is not possible to retrieve it later on.  OAuth 2.0 Clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) OAuth 2.0 Client ID 
     - parameter oAuth2Client: (body) OAuth 2.0 Client Request Body 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2Client> 
     */
    open class func setOAuth2ClientWithRequestBuilder(id: String, oAuth2Client: OAuth2Client, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2Client> {
        var localVariablePath = "/admin/clients/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: oAuth2Client, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2Client>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Set OAuth2 Client Token Lifespans
     
     - parameter id: (path) OAuth 2.0 Client ID 
     - parameter oAuth2ClientTokenLifespans: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuth2Client
     */
    open class func setOAuth2ClientLifespans(id: String, oAuth2ClientTokenLifespans: OAuth2ClientTokenLifespans? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuth2Client {
        return try await setOAuth2ClientLifespansWithRequestBuilder(id: id, oAuth2ClientTokenLifespans: oAuth2ClientTokenLifespans, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Set OAuth2 Client Token Lifespans
     - PUT /admin/clients/{id}/lifespans
     - Set lifespans of different token types issued for this OAuth 2.0 client. Does not modify other fields.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) OAuth 2.0 Client ID 
     - parameter oAuth2ClientTokenLifespans: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuth2Client> 
     */
    open class func setOAuth2ClientLifespansWithRequestBuilder(id: String, oAuth2ClientTokenLifespans: OAuth2ClientTokenLifespans? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OAuth2Client> {
        var localVariablePath = "/admin/clients/{id}/lifespans"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: oAuth2ClientTokenLifespans, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuth2Client>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Trust OAuth2 JWT Bearer Grant Type Issuer
     
     - parameter trustOAuth2JwtGrantIssuer: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TrustedOAuth2JwtGrantIssuer
     */
    open class func trustOAuth2JwtGrantIssuer(trustOAuth2JwtGrantIssuer: TrustOAuth2JwtGrantIssuer? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> TrustedOAuth2JwtGrantIssuer {
        return try await trustOAuth2JwtGrantIssuerWithRequestBuilder(trustOAuth2JwtGrantIssuer: trustOAuth2JwtGrantIssuer, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Trust OAuth2 JWT Bearer Grant Type Issuer
     - POST /admin/trust/grants/jwt-bearer/issuers
     - Use this endpoint to establish a trust relationship for a JWT issuer to perform JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grants [RFC7523](https://datatracker.ietf.org/doc/html/rfc7523).
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter trustOAuth2JwtGrantIssuer: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TrustedOAuth2JwtGrantIssuer> 
     */
    open class func trustOAuth2JwtGrantIssuerWithRequestBuilder(trustOAuth2JwtGrantIssuer: TrustOAuth2JwtGrantIssuer? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<TrustedOAuth2JwtGrantIssuer> {
        let localVariablePath = "/admin/trust/grants/jwt-bearer/issuers"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: trustOAuth2JwtGrantIssuer, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TrustedOAuth2JwtGrantIssuer>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
