//
// PermissionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PermissionAPI {

    /**
     Batch check permissions
     
     - parameter maxDepth: (query)  (optional)
     - parameter batchCheckPermissionBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BatchCheckPermissionResult
     */
    open class func batchCheckPermission(maxDepth: Int64? = nil, batchCheckPermissionBody: BatchCheckPermissionBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> BatchCheckPermissionResult {
        return try await batchCheckPermissionWithRequestBuilder(maxDepth: maxDepth, batchCheckPermissionBody: batchCheckPermissionBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Batch check permissions
     - POST /relation-tuples/batch/check
     - To learn how relationship tuples and the check works, head over to [the documentation](https://www.ory.sh/docs/keto/concepts/api-overview).
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter maxDepth: (query)  (optional)
     - parameter batchCheckPermissionBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BatchCheckPermissionResult> 
     */
    open class func batchCheckPermissionWithRequestBuilder(maxDepth: Int64? = nil, batchCheckPermissionBody: BatchCheckPermissionBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<BatchCheckPermissionResult> {
        let localVariablePath = "/relation-tuples/batch/check"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: batchCheckPermissionBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "max-depth": (wrappedValue: maxDepth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BatchCheckPermissionResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Check a permission
     
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter maxDepth: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CheckPermissionResult
     */
    open class func checkPermission(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, maxDepth: Int64? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> CheckPermissionResult {
        return try await checkPermissionWithRequestBuilder(namespace: namespace, object: object, relation: relation, subjectId: subjectId, subjectSetNamespace: subjectSetNamespace, subjectSetObject: subjectSetObject, subjectSetRelation: subjectSetRelation, maxDepth: maxDepth, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check a permission
     - GET /relation-tuples/check/openapi
     - To learn how relationship tuples and the check works, head over to [the documentation](https://www.ory.sh/docs/keto/concepts/api-overview).
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter maxDepth: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CheckPermissionResult> 
     */
    open class func checkPermissionWithRequestBuilder(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, maxDepth: Int64? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<CheckPermissionResult> {
        let localVariablePath = "/relation-tuples/check/openapi"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "namespace": (wrappedValue: namespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "object": (wrappedValue: object?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "relation": (wrappedValue: relation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_id": (wrappedValue: subjectId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.namespace": (wrappedValue: subjectSetNamespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.object": (wrappedValue: subjectSetObject?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.relation": (wrappedValue: subjectSetRelation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "max-depth": (wrappedValue: maxDepth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckPermissionResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Check a permission
     
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter maxDepth: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CheckPermissionResult
     */
    open class func checkPermissionOrError(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, maxDepth: Int64? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> CheckPermissionResult {
        return try await checkPermissionOrErrorWithRequestBuilder(namespace: namespace, object: object, relation: relation, subjectId: subjectId, subjectSetNamespace: subjectSetNamespace, subjectSetObject: subjectSetObject, subjectSetRelation: subjectSetRelation, maxDepth: maxDepth, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check a permission
     - GET /relation-tuples/check
     - To learn how relationship tuples and the check works, head over to [the documentation](https://www.ory.sh/docs/keto/concepts/api-overview).
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter maxDepth: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CheckPermissionResult> 
     */
    open class func checkPermissionOrErrorWithRequestBuilder(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, maxDepth: Int64? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<CheckPermissionResult> {
        let localVariablePath = "/relation-tuples/check"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "namespace": (wrappedValue: namespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "object": (wrappedValue: object?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "relation": (wrappedValue: relation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_id": (wrappedValue: subjectId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.namespace": (wrappedValue: subjectSetNamespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.object": (wrappedValue: subjectSetObject?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.relation": (wrappedValue: subjectSetRelation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "max-depth": (wrappedValue: maxDepth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckPermissionResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Expand a Relationship into permissions.
     
     - parameter namespace: (query) Namespace of the Subject Set 
     - parameter object: (query) Object of the Subject Set 
     - parameter relation: (query) Relation of the Subject Set 
     - parameter maxDepth: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ExpandedPermissionTree
     */
    open class func expandPermissions(namespace: String, object: String, relation: String, maxDepth: Int64? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> ExpandedPermissionTree {
        return try await expandPermissionsWithRequestBuilder(namespace: namespace, object: object, relation: relation, maxDepth: maxDepth, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Expand a Relationship into permissions.
     - GET /relation-tuples/expand
     - Use this endpoint to expand a relationship tuple into permissions.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter namespace: (query) Namespace of the Subject Set 
     - parameter object: (query) Object of the Subject Set 
     - parameter relation: (query) Relation of the Subject Set 
     - parameter maxDepth: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ExpandedPermissionTree> 
     */
    open class func expandPermissionsWithRequestBuilder(namespace: String, object: String, relation: String, maxDepth: Int64? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<ExpandedPermissionTree> {
        let localVariablePath = "/relation-tuples/expand"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "namespace": (wrappedValue: namespace.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "object": (wrappedValue: object.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "relation": (wrappedValue: relation.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "max-depth": (wrappedValue: maxDepth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ExpandedPermissionTree>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Check a permission
     
     - parameter maxDepth: (query)  (optional)
     - parameter postCheckPermissionBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CheckPermissionResult
     */
    open class func postCheckPermission(maxDepth: Int64? = nil, postCheckPermissionBody: PostCheckPermissionBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> CheckPermissionResult {
        return try await postCheckPermissionWithRequestBuilder(maxDepth: maxDepth, postCheckPermissionBody: postCheckPermissionBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check a permission
     - POST /relation-tuples/check/openapi
     - To learn how relationship tuples and the check works, head over to [the documentation](https://www.ory.sh/docs/keto/concepts/api-overview).
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter maxDepth: (query)  (optional)
     - parameter postCheckPermissionBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CheckPermissionResult> 
     */
    open class func postCheckPermissionWithRequestBuilder(maxDepth: Int64? = nil, postCheckPermissionBody: PostCheckPermissionBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<CheckPermissionResult> {
        let localVariablePath = "/relation-tuples/check/openapi"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postCheckPermissionBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "max-depth": (wrappedValue: maxDepth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckPermissionResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Check a permission
     
     - parameter maxDepth: (query)  (optional)
     - parameter postCheckPermissionOrErrorBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CheckPermissionResult
     */
    open class func postCheckPermissionOrError(maxDepth: Int64? = nil, postCheckPermissionOrErrorBody: PostCheckPermissionOrErrorBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> CheckPermissionResult {
        return try await postCheckPermissionOrErrorWithRequestBuilder(maxDepth: maxDepth, postCheckPermissionOrErrorBody: postCheckPermissionOrErrorBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check a permission
     - POST /relation-tuples/check
     - To learn how relationship tuples and the check works, head over to [the documentation](https://www.ory.sh/docs/keto/concepts/api-overview).
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter maxDepth: (query)  (optional)
     - parameter postCheckPermissionOrErrorBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CheckPermissionResult> 
     */
    open class func postCheckPermissionOrErrorWithRequestBuilder(maxDepth: Int64? = nil, postCheckPermissionOrErrorBody: PostCheckPermissionOrErrorBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<CheckPermissionResult> {
        let localVariablePath = "/relation-tuples/check"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postCheckPermissionOrErrorBody, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "max-depth": (wrappedValue: maxDepth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckPermissionResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
