//
// ProjectAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ProjectAPI {

    /**
     Create an Enterprise SSO Organization
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Organization
     */
    open class func createOrganization(projectId: String, organizationBody: OrganizationBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Organization {
        return try await createOrganizationWithRequestBuilder(projectId: projectId, organizationBody: organizationBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create an Enterprise SSO Organization
     - POST /projects/{project_id}/organizations
     - Deprecated: use setProject or patchProjectWithRevision instead  Creates an Enterprise SSO Organization in a project.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Organization> 
     */
    open class func createOrganizationWithRequestBuilder(projectId: String, organizationBody: OrganizationBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Organization> {
        var localVariablePath = "/projects/{project_id}/organizations"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: organizationBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Organization>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create organization onboarding portal link
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter createOrganizationOnboardingPortalLinkBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OnboardingPortalLink
     */
    open class func createOrganizationOnboardingPortalLink(projectId: String, organizationId: String, createOrganizationOnboardingPortalLinkBody: CreateOrganizationOnboardingPortalLinkBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OnboardingPortalLink {
        return try await createOrganizationOnboardingPortalLinkWithRequestBuilder(projectId: projectId, organizationId: organizationId, createOrganizationOnboardingPortalLinkBody: createOrganizationOnboardingPortalLinkBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create organization onboarding portal link
     - POST /projects/{project_id}/organizations/{organization_id}/onboarding-portal-links
     - Create a onboarding portal link for an organization.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter createOrganizationOnboardingPortalLinkBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OnboardingPortalLink> 
     */
    open class func createOrganizationOnboardingPortalLinkWithRequestBuilder(projectId: String, organizationId: String, createOrganizationOnboardingPortalLinkBody: CreateOrganizationOnboardingPortalLinkBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OnboardingPortalLink> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}/onboarding-portal-links"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createOrganizationOnboardingPortalLinkBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OnboardingPortalLink>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a Project
     
     - parameter createProjectBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Project
     */
    open class func createProject(createProjectBody: CreateProjectBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Project {
        return try await createProjectWithRequestBuilder(createProjectBody: createProjectBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a Project
     - POST /projects
     - Creates a new project.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter createProjectBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Project> 
     */
    open class func createProjectWithRequestBuilder(createProjectBody: CreateProjectBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Project> {
        let localVariablePath = "/projects"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createProjectBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Project>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create project API key
     
     - parameter project: (path) The Project ID or Project slug 
     - parameter createProjectApiKeyRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ProjectApiKey
     */
    open class func createProjectApiKey(project: String, createProjectApiKeyRequest: CreateProjectApiKeyRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> ProjectApiKey {
        return try await createProjectApiKeyWithRequestBuilder(project: project, createProjectApiKeyRequest: createProjectApiKeyRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create project API key
     - POST /projects/{project}/tokens
     - Create an API key for a project.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter project: (path) The Project ID or Project slug 
     - parameter createProjectApiKeyRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ProjectApiKey> 
     */
    open class func createProjectApiKeyWithRequestBuilder(project: String, createProjectApiKeyRequest: CreateProjectApiKeyRequest? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<ProjectApiKey> {
        var localVariablePath = "/projects/{project}/tokens"
        let projectPreEscape = "\(APIHelper.mapValueToPathItem(project))"
        let projectPostEscape = projectPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project}", with: projectPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createProjectApiKeyRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProjectApiKey>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete Enterprise SSO Organization
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteOrganization(projectId: String, organizationId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteOrganizationWithRequestBuilder(projectId: projectId, organizationId: organizationId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete Enterprise SSO Organization
     - DELETE /projects/{project_id}/organizations/{organization_id}
     - Deprecated: use setProject or patchProjectWithRevision instead  Irrecoverably deletes an Enterprise SSO Organization in a project by its ID.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteOrganizationWithRequestBuilder(projectId: String, organizationId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete an organization onboarding portal link
     
     - parameter projectId: (path)  
     - parameter organizationId: (path)  
     - parameter onboardingPortalLinkId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteOrganizationOnboardingPortalLink(projectId: String, organizationId: String, onboardingPortalLinkId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteOrganizationOnboardingPortalLinkWithRequestBuilder(projectId: projectId, organizationId: organizationId, onboardingPortalLinkId: onboardingPortalLinkId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete an organization onboarding portal link
     - DELETE /projects/{project_id}/organizations/{organization_id}/onboarding-portal-links/{onboarding_portal_link_id}
     - Deletes a onboarding portal link for an organization.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path)  
     - parameter organizationId: (path)  
     - parameter onboardingPortalLinkId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteOrganizationOnboardingPortalLinkWithRequestBuilder(projectId: String, organizationId: String, onboardingPortalLinkId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}/onboarding-portal-links/{onboarding_portal_link_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let onboardingPortalLinkIdPreEscape = "\(APIHelper.mapValueToPathItem(onboardingPortalLinkId))"
        let onboardingPortalLinkIdPostEscape = onboardingPortalLinkIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{onboarding_portal_link_id}", with: onboardingPortalLinkIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete project API key
     
     - parameter project: (path) The Project ID or Project slug 
     - parameter tokenId: (path) The Token ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteProjectApiKey(project: String, tokenId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteProjectApiKeyWithRequestBuilder(project: project, tokenId: tokenId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete project API key
     - DELETE /projects/{project}/tokens/{token_id}
     - Deletes an API key and immediately removes it.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter project: (path) The Project ID or Project slug 
     - parameter tokenId: (path) The Token ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteProjectApiKeyWithRequestBuilder(project: String, tokenId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/projects/{project}/tokens/{token_id}"
        let projectPreEscape = "\(APIHelper.mapValueToPathItem(project))"
        let projectPostEscape = projectPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project}", with: projectPostEscape, options: .literal, range: nil)
        let tokenIdPreEscape = "\(APIHelper.mapValueToPathItem(tokenId))"
        let tokenIdPostEscape = tokenIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{token_id}", with: tokenIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get Enterprise SSO Organization by ID
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetOrganizationResponse
     */
    open class func getOrganization(projectId: String, organizationId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetOrganizationResponse {
        return try await getOrganizationWithRequestBuilder(projectId: projectId, organizationId: organizationId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get Enterprise SSO Organization by ID
     - GET /projects/{project_id}/organizations/{organization_id}
     - Deprecated: use getProject instead  Retrieves an Enterprise SSO Organization for a project by its ID
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetOrganizationResponse> 
     */
    open class func getOrganizationWithRequestBuilder(projectId: String, organizationId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<GetOrganizationResponse> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOrganizationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get the organization onboarding portal links
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OrganizationOnboardingPortalLinksResponse
     */
    open class func getOrganizationOnboardingPortalLinks(projectId: String, organizationId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OrganizationOnboardingPortalLinksResponse {
        return try await getOrganizationOnboardingPortalLinksWithRequestBuilder(projectId: projectId, organizationId: organizationId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get the organization onboarding portal links
     - GET /projects/{project_id}/organizations/{organization_id}/onboarding-portal-links
     - Retrieves the organization onboarding portal links.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OrganizationOnboardingPortalLinksResponse> 
     */
    open class func getOrganizationOnboardingPortalLinksWithRequestBuilder(projectId: String, organizationId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OrganizationOnboardingPortalLinksResponse> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}/onboarding-portal-links"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OrganizationOnboardingPortalLinksResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a Project
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Project
     */
    open class func getProject(projectId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Project {
        return try await getProjectWithRequestBuilder(projectId: projectId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a Project
     - GET /projects/{project_id}
     - Get a project you have access to by its ID.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Project> 
     */
    open class func getProjectWithRequestBuilder(projectId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Project> {
        var localVariablePath = "/projects/{project_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Project>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get all members associated with this project
     
     - parameter project: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProjectMember]
     */
    open class func getProjectMembers(project: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [ProjectMember] {
        return try await getProjectMembersWithRequestBuilder(project: project, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all members associated with this project
     - GET /projects/{project}/members
     - This endpoint requires the user to be a member of the project with the role `OWNER` or `DEVELOPER`.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter project: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProjectMember]> 
     */
    open class func getProjectMembersWithRequestBuilder(project: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[ProjectMember]> {
        var localVariablePath = "/projects/{project}/members"
        let projectPreEscape = "\(APIHelper.mapValueToPathItem(project))"
        let projectPostEscape = projectPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project}", with: projectPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProjectMember]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List all Enterprise SSO organizations
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter domain: (query) Domain  If set, only organizations with that domain will be returned. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListOrganizationsResponse
     */
    open class func listOrganizations(projectId: String, pageSize: Int64? = nil, pageToken: String? = nil, domain: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> ListOrganizationsResponse {
        return try await listOrganizationsWithRequestBuilder(projectId: projectId, pageSize: pageSize, pageToken: pageToken, domain: domain, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all Enterprise SSO organizations
     - GET /projects/{project_id}/organizations
     - Deprecated: use getProject instead  Lists all Enterprise SSO organizations in a project.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter domain: (query) Domain  If set, only organizations with that domain will be returned. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListOrganizationsResponse> 
     */
    open class func listOrganizationsWithRequestBuilder(projectId: String, pageSize: Int64? = nil, pageToken: String? = nil, domain: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<ListOrganizationsResponse> {
        var localVariablePath = "/projects/{project_id}/organizations"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_token": (wrappedValue: pageToken?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "domain": (wrappedValue: domain?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListOrganizationsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List a project's API keys
     
     - parameter project: (path) The Project ID or Project slug 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProjectApiKey]
     */
    open class func listProjectApiKeys(project: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [ProjectApiKey] {
        return try await listProjectApiKeysWithRequestBuilder(project: project, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List a project's API keys
     - GET /projects/{project}/tokens
     - A list of all the project's API keys.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter project: (path) The Project ID or Project slug 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProjectApiKey]> 
     */
    open class func listProjectApiKeysWithRequestBuilder(project: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[ProjectApiKey]> {
        var localVariablePath = "/projects/{project}/tokens"
        let projectPreEscape = "\(APIHelper.mapValueToPathItem(project))"
        let projectPostEscape = projectPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project}", with: projectPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProjectApiKey]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List All Projects
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ProjectMetadata]
     */
    open class func listProjects(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [ProjectMetadata] {
        return try await listProjectsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List All Projects
     - GET /projects
     - Lists all projects you have access to.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ProjectMetadata]> 
     */
    open class func listProjectsWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[ProjectMetadata]> {
        let localVariablePath = "/projects"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProjectMetadata]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Patch an Ory Network Project Configuration
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter jsonPatch: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SuccessfulProjectUpdate
     */
    open class func patchProject(projectId: String, jsonPatch: [JsonPatch]? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> SuccessfulProjectUpdate {
        return try await patchProjectWithRequestBuilder(projectId: projectId, jsonPatch: jsonPatch, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Patch an Ory Network Project Configuration
     - PATCH /projects/{project_id}
     - Deprecated: Use the `patchProjectWithRevision` endpoint instead to specify the exact revision the patch was generated for.  This endpoints allows you to patch individual Ory Network project configuration keys for Ory's services (identity, permission, ...). The configuration format is fully compatible with the open source projects for the respective services (e.g. Ory Kratos for Identity, Ory Keto for Permissions).  This endpoint expects the `version` key to be set in the payload. If it is unset, it will try to import the config as if it is from the most recent version.  If you have an older version of a configuration, you should set the version key in the payload!  While this endpoint is able to process all configuration items related to features (e.g. password reset), it does not support operational configuration items (e.g. port, tracing, logging) otherwise available in the open source.  For configuration items that can not be translated to the Ory Network, this endpoint will return a list of warnings to help you understand which parts of your config could not be processed.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter jsonPatch: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SuccessfulProjectUpdate> 
     */
    open class func patchProjectWithRequestBuilder(projectId: String, jsonPatch: [JsonPatch]? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<SuccessfulProjectUpdate> {
        var localVariablePath = "/projects/{project_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: jsonPatch, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessfulProjectUpdate>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Patch an Ory Network Project Configuration based on a revision ID
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter revisionId: (path) Revision ID  The revision ID that this patch was generated for. 
     - parameter jsonPatch: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SuccessfulProjectUpdate
     */
    open class func patchProjectWithRevision(projectId: String, revisionId: String, jsonPatch: [JsonPatch]? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> SuccessfulProjectUpdate {
        return try await patchProjectWithRevisionWithRequestBuilder(projectId: projectId, revisionId: revisionId, jsonPatch: jsonPatch, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Patch an Ory Network Project Configuration based on a revision ID
     - PATCH /projects/{project_id}/revision/{revision_id}
     - This endpoints allows you to patch individual Ory Network Project configuration keys for Ory's services (identity, permission, ...). The configuration format is fully compatible with the open source projects for the respective services (e.g. Ory Kratos for Identity, Ory Keto for Permissions).  This endpoint expects the `version` key to be set in the payload. If it is unset, it will try to import the config as if it is from the most recent version.  If you have an older version of a configuration, you should set the version key in the payload!  While this endpoint is able to process all configuration items related to features (e.g. password reset), it does not support operational configuration items (e.g. port, tracing, logging) otherwise available in the open source.  For configuration items that can not be translated to the Ory Network, this endpoint will return a list of warnings to help you understand which parts of your config could not be processed.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter revisionId: (path) Revision ID  The revision ID that this patch was generated for. 
     - parameter jsonPatch: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SuccessfulProjectUpdate> 
     */
    open class func patchProjectWithRevisionWithRequestBuilder(projectId: String, revisionId: String, jsonPatch: [JsonPatch]? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<SuccessfulProjectUpdate> {
        var localVariablePath = "/projects/{project_id}/revision/{revision_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let revisionIdPreEscape = "\(APIHelper.mapValueToPathItem(revisionId))"
        let revisionIdPostEscape = revisionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{revision_id}", with: revisionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: jsonPatch, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessfulProjectUpdate>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Irrecoverably purge a project
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func purgeProject(projectId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await purgeProjectWithRequestBuilder(projectId: projectId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Irrecoverably purge a project
     - DELETE /projects/{project_id}
     - !! Use with extreme caution !!  Using this API endpoint you can purge (completely delete) a project and its data. This action can not be undone and will delete ALL your data.  Calling this endpoint will additionally delete custom domains and other related data.  If the project is linked to a subscription, the subscription needs to be unlinked first.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func purgeProjectWithRequestBuilder(projectId: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/projects/{project_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Remove a member associated with this project
     
     - parameter project: (path)  
     - parameter member: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func removeProjectMember(project: String, member: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await removeProjectMemberWithRequestBuilder(project: project, member: member, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove a member associated with this project
     - DELETE /projects/{project}/members/{member}
     - This also sets their invite status to `REMOVED`. This endpoint requires the user to be a member of the project with the role `OWNER`.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter project: (path)  
     - parameter member: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func removeProjectMemberWithRequestBuilder(project: String, member: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/projects/{project}/members/{member}"
        let projectPreEscape = "\(APIHelper.mapValueToPathItem(project))"
        let projectPostEscape = projectPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project}", with: projectPostEscape, options: .literal, range: nil)
        let memberPreEscape = "\(APIHelper.mapValueToPathItem(member))"
        let memberPostEscape = memberPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{member}", with: memberPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an Ory Network Project Configuration
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter setProject: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SuccessfulProjectUpdate
     */
    open class func setProject(projectId: String, setProject: SetProject? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> SuccessfulProjectUpdate {
        return try await setProjectWithRequestBuilder(projectId: projectId, setProject: setProject, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an Ory Network Project Configuration
     - PUT /projects/{project_id}
     - This endpoints allows you to update the Ory Network project configuration for individual services (identity, permission, ...). The configuration is fully compatible with the open source projects for the respective services (e.g. Ory Kratos for Identity, Ory Keto for Permissions).  This endpoint expects the `version` key to be set in the payload. If it is unset, it will try to import the config as if it is from the most recent version.  If you have an older version of a configuration, you should set the version key in the payload!  While this endpoint is able to process all configuration items related to features (e.g. password reset), it does not support operational configuration items (e.g. port, tracing, logging) otherwise available in the open source.  For configuration items that can not be translated to the Ory Network, this endpoint will return a list of warnings to help you understand which parts of your config could not be processed.  Be aware that updating any service's configuration will completely override your current configuration for that service!
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter setProject: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SuccessfulProjectUpdate> 
     */
    open class func setProjectWithRequestBuilder(projectId: String, setProject: SetProject? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<SuccessfulProjectUpdate> {
        var localVariablePath = "/projects/{project_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setProject, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessfulProjectUpdate>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an Enterprise SSO Organization
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter organizationBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Organization
     */
    open class func updateOrganization(projectId: String, organizationId: String, organizationBody: OrganizationBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Organization {
        return try await updateOrganizationWithRequestBuilder(projectId: projectId, organizationId: organizationId, organizationBody: organizationBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an Enterprise SSO Organization
     - PUT /projects/{project_id}/organizations/{organization_id}
     - Deprecated: use setProject or patchProjectWithRevision instead  Updates an Enterprise SSO Organization in a project by its ID.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter organizationBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Organization> 
     */
    open class func updateOrganizationWithRequestBuilder(projectId: String, organizationId: String, organizationBody: OrganizationBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Organization> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: organizationBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Organization>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update organization onboarding portal link
     
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter onboardingPortalLinkId: (path)  
     - parameter updateOrganizationOnboardingPortalLinkBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OnboardingPortalLink
     */
    open class func updateOrganizationOnboardingPortalLink(projectId: String, organizationId: String, onboardingPortalLinkId: String, updateOrganizationOnboardingPortalLinkBody: UpdateOrganizationOnboardingPortalLinkBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> OnboardingPortalLink {
        return try await updateOrganizationOnboardingPortalLinkWithRequestBuilder(projectId: projectId, organizationId: organizationId, onboardingPortalLinkId: onboardingPortalLinkId, updateOrganizationOnboardingPortalLinkBody: updateOrganizationOnboardingPortalLinkBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update organization onboarding portal link
     - POST /projects/{project_id}/organizations/{organization_id}/onboarding-portal-links/{onboarding_portal_link_id}
     - Update a onboarding portal link for an organization.
     - Bearer Token:
       - type: http
       - name: oryWorkspaceApiKey
     - parameter projectId: (path) Project ID  The project&#39;s ID. 
     - parameter organizationId: (path) Organization ID  The Organization&#39;s ID. 
     - parameter onboardingPortalLinkId: (path)  
     - parameter updateOrganizationOnboardingPortalLinkBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OnboardingPortalLink> 
     */
    open class func updateOrganizationOnboardingPortalLinkWithRequestBuilder(projectId: String, organizationId: String, onboardingPortalLinkId: String, updateOrganizationOnboardingPortalLinkBody: UpdateOrganizationOnboardingPortalLinkBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<OnboardingPortalLink> {
        var localVariablePath = "/projects/{project_id}/organizations/{organization_id}/onboarding-portal-links/{onboarding_portal_link_id}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{project_id}", with: projectIdPostEscape, options: .literal, range: nil)
        let organizationIdPreEscape = "\(APIHelper.mapValueToPathItem(organizationId))"
        let organizationIdPostEscape = organizationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{organization_id}", with: organizationIdPostEscape, options: .literal, range: nil)
        let onboardingPortalLinkIdPreEscape = "\(APIHelper.mapValueToPathItem(onboardingPortalLinkId))"
        let onboardingPortalLinkIdPostEscape = onboardingPortalLinkIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{onboarding_portal_link_id}", with: onboardingPortalLinkIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateOrganizationOnboardingPortalLinkBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OnboardingPortalLink>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
