//
// WellknownAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class WellknownAPI {

    /**
     Discover Well-Known JSON Web Keys
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JsonWebKeySet
     */
    open class func discoverJsonWebKeys(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> JsonWebKeySet {
        return try await discoverJsonWebKeysWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Discover Well-Known JSON Web Keys
     - GET /.well-known/jwks.json
     - This endpoint returns JSON Web Keys required to verifying OpenID Connect ID Tokens and, if enabled, OAuth 2.0 JWT Access Tokens. This endpoint can be used with client libraries like [node-jwks-rsa](https://github.com/auth0/node-jwks-rsa) among others.  Adding custom keys requires first creating a keyset via the createJsonWebKeySet operation, and then configuring the webfinger.jwks.broadcast_keys configuration value to include the keyset name.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JsonWebKeySet> 
     */
    open class func discoverJsonWebKeysWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<JsonWebKeySet> {
        let localVariablePath = "/.well-known/jwks.json"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JsonWebKeySet>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
