//
// AccountExperienceConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AccountExperienceConfiguration: Sendable, Codable, Hashable {

    public enum LocaleBehavior: String, Sendable, Codable, CaseIterable {
        case forceDefault = "force_default"
        case respectAcceptLanguage = "respect_accept_language"
    }
    public var defaultLocale: String
    public var defaultRedirectUrl: String
    public var enabledLocales: [String]
    public var errorUiUrl: String
    public var faviconDarkUrl: String?
    public var faviconLightUrl: String?
    /**  force_default AccountExperienceLocaleBehaviorForceDefault respect_accept_language AccountExperienceLocaleBehaviorRespectAcceptLanguage */
    public var localeBehavior: LocaleBehavior
    public var loginUiUrl: String
    public var logoDarkUrl: String?
    public var logoLightUrl: String?
    public var name: String
    public var recoveryEnabled: Bool
    public var recoveryUiUrl: String
    public var registrationEnabled: Bool
    public var registrationUiUrl: String
    public var settingsUiUrl: String
    public var stylesheet: String?
    public var translations: [RevisionAccountExperienceCustomTranslation]
    public var verificationEnabled: Bool
    public var verificationUiUrl: String

    public init(defaultLocale: String, defaultRedirectUrl: String, enabledLocales: [String], errorUiUrl: String, faviconDarkUrl: String? = nil, faviconLightUrl: String? = nil, localeBehavior: LocaleBehavior, loginUiUrl: String, logoDarkUrl: String? = nil, logoLightUrl: String? = nil, name: String, recoveryEnabled: Bool, recoveryUiUrl: String, registrationEnabled: Bool, registrationUiUrl: String, settingsUiUrl: String, stylesheet: String? = nil, translations: [RevisionAccountExperienceCustomTranslation], verificationEnabled: Bool, verificationUiUrl: String) {
        self.defaultLocale = defaultLocale
        self.defaultRedirectUrl = defaultRedirectUrl
        self.enabledLocales = enabledLocales
        self.errorUiUrl = errorUiUrl
        self.faviconDarkUrl = faviconDarkUrl
        self.faviconLightUrl = faviconLightUrl
        self.localeBehavior = localeBehavior
        self.loginUiUrl = loginUiUrl
        self.logoDarkUrl = logoDarkUrl
        self.logoLightUrl = logoLightUrl
        self.name = name
        self.recoveryEnabled = recoveryEnabled
        self.recoveryUiUrl = recoveryUiUrl
        self.registrationEnabled = registrationEnabled
        self.registrationUiUrl = registrationUiUrl
        self.settingsUiUrl = settingsUiUrl
        self.stylesheet = stylesheet
        self.translations = translations
        self.verificationEnabled = verificationEnabled
        self.verificationUiUrl = verificationUiUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defaultLocale = "default_locale"
        case defaultRedirectUrl = "default_redirect_url"
        case enabledLocales = "enabled_locales"
        case errorUiUrl = "error_ui_url"
        case faviconDarkUrl = "favicon_dark_url"
        case faviconLightUrl = "favicon_light_url"
        case localeBehavior = "locale_behavior"
        case loginUiUrl = "login_ui_url"
        case logoDarkUrl = "logo_dark_url"
        case logoLightUrl = "logo_light_url"
        case name
        case recoveryEnabled = "recovery_enabled"
        case recoveryUiUrl = "recovery_ui_url"
        case registrationEnabled = "registration_enabled"
        case registrationUiUrl = "registration_ui_url"
        case settingsUiUrl = "settings_ui_url"
        case stylesheet
        case translations
        case verificationEnabled = "verification_enabled"
        case verificationUiUrl = "verification_ui_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(defaultLocale, forKey: .defaultLocale)
        try container.encode(defaultRedirectUrl, forKey: .defaultRedirectUrl)
        try container.encode(enabledLocales, forKey: .enabledLocales)
        try container.encode(errorUiUrl, forKey: .errorUiUrl)
        try container.encodeIfPresent(faviconDarkUrl, forKey: .faviconDarkUrl)
        try container.encodeIfPresent(faviconLightUrl, forKey: .faviconLightUrl)
        try container.encode(localeBehavior, forKey: .localeBehavior)
        try container.encode(loginUiUrl, forKey: .loginUiUrl)
        try container.encodeIfPresent(logoDarkUrl, forKey: .logoDarkUrl)
        try container.encodeIfPresent(logoLightUrl, forKey: .logoLightUrl)
        try container.encode(name, forKey: .name)
        try container.encode(recoveryEnabled, forKey: .recoveryEnabled)
        try container.encode(recoveryUiUrl, forKey: .recoveryUiUrl)
        try container.encode(registrationEnabled, forKey: .registrationEnabled)
        try container.encode(registrationUiUrl, forKey: .registrationUiUrl)
        try container.encode(settingsUiUrl, forKey: .settingsUiUrl)
        try container.encodeIfPresent(stylesheet, forKey: .stylesheet)
        try container.encode(translations, forKey: .translations)
        try container.encode(verificationEnabled, forKey: .verificationEnabled)
        try container.encode(verificationUiUrl, forKey: .verificationUiUrl)
    }
}

