//
// AddProjectToWorkspaceBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddProjectToWorkspaceBody: Sendable, Codable, Hashable {

    public enum Environment: String, Sendable, Codable, CaseIterable {
        case prod = "prod"
        case stage = "stage"
        case dev = "dev"
    }
    public enum ProjectSubscription: String, Sendable, Codable, CaseIterable {
        case migrate = "migrate"
        case ignore = "ignore"
    }
    /** The environment of the project in the workspace. Can be one of \"prod\" or \"dev\". Note that the number of projects in the \"prod\" environment is limited depending on the subscription. prod Production stage Staging dev Development */
    public var environment: Environment
    /** The action to take with the project subscription. Can be one of \"migrate\", and \"ignore\". \"migrate\" will migrate the project subscription to the workspace. \"ignore\" will ignore the project subscription. migrate ProjectSubscriptionActionMigrate  ProjectSubscriptionActionMigrate will migrate the project subscription to the  workspace. ignore ProjectSubscriptionActionIgnore  ProjectSubscriptionActionIgnore will ignore the project subscription. */
    public var projectSubscription: ProjectSubscription

    public init(environment: Environment, projectSubscription: ProjectSubscription) {
        self.environment = environment
        self.projectSubscription = projectSubscription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case environment
        case projectSubscription = "project_subscription"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(environment, forKey: .environment)
        try container.encode(projectSubscription, forKey: .projectSubscription)
    }
}

