//
// AttributesCountDatapoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AttributesCountDatapoint: Sendable, Codable, Hashable {

    /** Count of the attribute value for given key */
    public var count: Int64
    /** Name of the attribute value for given key */
    public var name: String

    public init(count: Int64, name: String) {
        self.count = count
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(name, forKey: .name)
    }
}

