//
// BatchCheckPermissionBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Batch Check Permission Body */
public struct BatchCheckPermissionBody: Sendable, Codable, Hashable {

    public var tuples: [Relationship]?

    public init(tuples: [Relationship]? = nil) {
        self.tuples = tuples
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tuples
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tuples, forKey: .tuples)
    }
}

