//
// BillingPeriodBucket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BillingPeriodBucket: Sendable, Codable, Hashable {

    public var baseInvoices: [Invoice]?
    public var billingPeriod: TimeInterval?
    public var usageInvoice: Invoice?

    public init(baseInvoices: [Invoice]? = nil, billingPeriod: TimeInterval? = nil, usageInvoice: Invoice? = nil) {
        self.baseInvoices = baseInvoices
        self.billingPeriod = billingPeriod
        self.usageInvoice = usageInvoice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case baseInvoices = "base_invoices"
        case billingPeriod = "billing_period"
        case usageInvoice = "usage_invoice"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(baseInvoices, forKey: .baseInvoices)
        try container.encodeIfPresent(billingPeriod, forKey: .billingPeriod)
        try container.encodeIfPresent(usageInvoice, forKey: .usageInvoice)
    }
}

