//
// CheckPermissionResultWithError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Check Permission Result With Error */
public struct CheckPermissionResultWithError: Sendable, Codable, Hashable {

    /** whether the relation tuple is allowed */
    public var allowed: Bool
    /** any error generated while checking the relation tuple */
    public var error: String?

    public init(allowed: Bool, error: String? = nil) {
        self.allowed = allowed
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowed
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowed, forKey: .allowed)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

