//
// ContinueWith.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ContinueWith: Sendable, Codable, Hashable {
    case typeContinueWithRecoveryUi(ContinueWithRecoveryUi)
    case typeContinueWithRedirectBrowserTo(ContinueWithRedirectBrowserTo)
    case typeContinueWithSetOrySessionToken(ContinueWithSetOrySessionToken)
    case typeContinueWithSettingsUi(ContinueWithSettingsUi)
    case typeContinueWithVerificationUi(ContinueWithVerificationUi)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeContinueWithRecoveryUi(let value):
            try container.encode(value)
        case .typeContinueWithRedirectBrowserTo(let value):
            try container.encode(value)
        case .typeContinueWithSetOrySessionToken(let value):
            try container.encode(value)
        case .typeContinueWithSettingsUi(let value):
            try container.encode(value)
        case .typeContinueWithVerificationUi(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case action = "action"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .action)

        switch discriminatorValue {
        case "redirect_browser_to":
            self = .typeContinueWithRedirectBrowserTo(try ContinueWithRedirectBrowserTo(from: decoder))
        case "set_ory_session_token":
            self = .typeContinueWithSetOrySessionToken(try ContinueWithSetOrySessionToken(from: decoder))
        case "show_recovery_ui":
            self = .typeContinueWithRecoveryUi(try ContinueWithRecoveryUi(from: decoder))
        case "show_settings_ui":
            self = .typeContinueWithSettingsUi(try ContinueWithSettingsUi(from: decoder))
        case "show_verification_ui":
            self = .typeContinueWithVerificationUi(try ContinueWithVerificationUi(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for ContinueWith"
                )
            )
        }
    }
}

