//
// ContinueWithRedirectBrowserTo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Indicates, that the UI flow could be continued by showing a recovery ui */
public struct ContinueWithRedirectBrowserTo: Sendable, Codable, Hashable {

    public enum Action: String, Sendable, Codable, CaseIterable {
        case redirectBrowserTo = "redirect_browser_to"
    }
    /** Action will always be `redirect_browser_to` redirect_browser_to ContinueWithActionRedirectBrowserToString */
    public var action: Action
    /** The URL to redirect the browser to */
    public var redirectBrowserTo: String

    public init(action: Action, redirectBrowserTo: String) {
        self.action = action
        self.redirectBrowserTo = redirectBrowserTo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case redirectBrowserTo = "redirect_browser_to"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(redirectBrowserTo, forKey: .redirectBrowserTo)
    }
}

