//
// CreateProjectMemberInviteBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Create Project MemberInvite Request Body */
public struct CreateProjectMemberInviteBody: Sendable, Codable, Hashable {

    /** A email to invite */
    public var inviteeEmail: String?

    public init(inviteeEmail: String? = nil) {
        self.inviteeEmail = inviteeEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inviteeEmail = "invitee_email"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inviteeEmail, forKey: .inviteeEmail)
    }
}

