//
// CreateWorkspaceMemberInviteBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Create Workspace Invite Request Body */
public struct CreateWorkspaceMemberInviteBody: Sendable, Codable, Hashable {

    public enum Role: String, Sendable, Codable, CaseIterable {
        case owner = "owner"
        case developer = "developer"
    }
    /** A email to invite */
    public var inviteeEmail: String
    /** The role the user will have in the workspace owner WorkspaceMemberRoleOwner developer WorkspaceMemberRoleDeveloper */
    public var role: Role

    public init(inviteeEmail: String, role: Role) {
        self.inviteeEmail = inviteeEmail
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inviteeEmail = "invitee_email"
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inviteeEmail, forKey: .inviteeEmail)
        try container.encode(role, forKey: .role)
    }
}

