//
// CreateSubscriptionBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateSubscriptionBody: Sendable, Codable, Hashable {

    public enum Currency: String, Sendable, Codable, CaseIterable {
        case usd = "usd"
        case eur = "eur"
    }
    public enum Interval: String, Sendable, Codable, CaseIterable {
        case monthly = "monthly"
        case yearly = "yearly"
    }
    /**  usd USD eur Euro */
    public var currency: Currency?
    /**  monthly Monthly yearly Yearly */
    public var interval: Interval
    public var plan: String
    public var provisionFirstProject: String
    public var returnTo: String?

    public init(currency: Currency? = nil, interval: Interval, plan: String, provisionFirstProject: String, returnTo: String? = nil) {
        self.currency = currency
        self.interval = interval
        self.plan = plan
        self.provisionFirstProject = provisionFirstProject
        self.returnTo = returnTo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case interval
        case plan
        case provisionFirstProject = "provision_first_project"
        case returnTo = "return_to"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encode(interval, forKey: .interval)
        try container.encode(plan, forKey: .plan)
        try container.encode(provisionFirstProject, forKey: .provisionFirstProject)
        try container.encodeIfPresent(returnTo, forKey: .returnTo)
    }
}

