//
// CreateVerifiableCredentialRequestBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateVerifiableCredentialRequestBody: Sendable, Codable, Hashable {

    public var format: String?
    public var proof: VerifiableCredentialProof?
    public var types: [String]?

    public init(format: String? = nil, proof: VerifiableCredentialProof? = nil, types: [String]? = nil) {
        self.format = format
        self.proof = proof
        self.types = types
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case format
        case proof
        case types
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(proof, forKey: .proof)
        try container.encodeIfPresent(types, forKey: .types)
    }
}

