//
// CreateProjectBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Create Project Request Body */
public struct CreateProjectBody: Sendable, Codable, Hashable {

    public enum Environment: String, Sendable, Codable, CaseIterable {
        case prod = "prod"
        case stage = "stage"
        case dev = "dev"
    }
    public enum HomeRegion: String, Sendable, Codable, CaseIterable {
        case euCentral = "eu-central"
        case asiaNortheast = "asia-northeast"
        case usEast = "us-east"
        case usWest = "us-west"
        case us = "us"
        case global = "global"
    }
    /** The environment of the project. prod Production stage Staging dev Development */
    public var environment: Environment
    /** Home Region  The home region of the project. This is the region where the project will be created. eu-central EUCentral asia-northeast AsiaNorthEast us-east USEast us-west USWest us US global Global */
    public var homeRegion: HomeRegion?
    /** The name of the project to be created */
    public var name: String
    /** The workspace to create the project in. */
    public var workspaceId: String?

    public init(environment: Environment, homeRegion: HomeRegion? = nil, name: String, workspaceId: String? = nil) {
        self.environment = environment
        self.homeRegion = homeRegion
        self.name = name
        self.workspaceId = workspaceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case environment
        case homeRegion = "home_region"
        case name
        case workspaceId = "workspace_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(environment, forKey: .environment)
        try container.encodeIfPresent(homeRegion, forKey: .homeRegion)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
    }
}

