//
// CreateOrganizationOnboardingPortalLinkBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateOrganizationOnboardingPortalLinkBody: Sendable, Codable, Hashable {

    /** AppleMapper specifies the JSONNet code snippet which uses Apple's profile information to hydrate the identity's data. */
    public var appleMapperUrl: String?
    /** Auth0Mapper specifies the JSONNet code snippet which uses Auth0's profile information to hydrate the identity's data. */
    public var auth0MapperUrl: String?
    public var customHostnameId: String?
    /** Feature flag to enable SCIM configuration */
    public var enableScim: Bool
    /** Feature flag to enable SSO configuration */
    public var enableSso: Bool
    public var expiresAt: Date?
    /** FacebookMapper specifies the JSONNet code snippet which uses Facebook's profile information to hydrate the identity's data. */
    public var facebookMapperUrl: String?
    /** GenericOIDCMapper specifies the JSONNet code snippet which uses the OIDC Provider's profile information to hydrate the identity's data. */
    public var genericOidcMapperUrl: String?
    /** GithubMapper specifies the JSONNet code snippet which uses GitHub's profile information to hydrate the identity's data. */
    public var githubMapperUrl: String?
    /** GitLabMapper specifies the JSONNet code snippet which uses GitLab's profile information to hydrate the identity's data. */
    public var gitlabMapperUrl: String?
    /** GoogleMapper specifies the JSONNet code snippet which uses Google's profile information to hydrate the identity's data. */
    public var googleMapperUrl: String?
    /** MicrosoftMapper specifies the JSONNet code snippet which uses Microsoft's profile information to hydrate the identity's data. */
    public var microsoftMapperUrl: String?
    /** NetIDMapper specifies the JSONNet code snippet which uses NetID's profile information to hydrate the identity's data. */
    public var netidMapperUrl: String?
    /** Proxy ACS URL if overriding with a customer-controlled URL */
    public var proxyAcsUrl: String?
    /** Proxy OIDC Redirect URL if overriding with a customer-controlled URL */
    public var proxyOidcRedirectUrl: String?
    /** SAML Audience Override if overriding with a customer-controlled one */
    public var proxySamlAudienceOverride: String?
    /** Proxy SCIM Server URL if overriding with a customer-controlled URL */
    public var proxyScimServerUrl: String?
    /** SAMLMapper specifies the JSONNet code snippet which uses the SAML Provider's profile information to hydrate the identity's data. */
    public var samlMapperUrl: String?
    /** SCIMMapper specifies the JSONNet code snippet which uses the SCIM Provider's profile information to hydrate the identity's data. */
    public var scimMapperUrl: String?

    public init(appleMapperUrl: String? = nil, auth0MapperUrl: String? = nil, customHostnameId: String? = nil, enableScim: Bool, enableSso: Bool, expiresAt: Date? = nil, facebookMapperUrl: String? = nil, genericOidcMapperUrl: String? = nil, githubMapperUrl: String? = nil, gitlabMapperUrl: String? = nil, googleMapperUrl: String? = nil, microsoftMapperUrl: String? = nil, netidMapperUrl: String? = nil, proxyAcsUrl: String? = nil, proxyOidcRedirectUrl: String? = nil, proxySamlAudienceOverride: String? = nil, proxyScimServerUrl: String? = nil, samlMapperUrl: String? = nil, scimMapperUrl: String? = nil) {
        self.appleMapperUrl = appleMapperUrl
        self.auth0MapperUrl = auth0MapperUrl
        self.customHostnameId = customHostnameId
        self.enableScim = enableScim
        self.enableSso = enableSso
        self.expiresAt = expiresAt
        self.facebookMapperUrl = facebookMapperUrl
        self.genericOidcMapperUrl = genericOidcMapperUrl
        self.githubMapperUrl = githubMapperUrl
        self.gitlabMapperUrl = gitlabMapperUrl
        self.googleMapperUrl = googleMapperUrl
        self.microsoftMapperUrl = microsoftMapperUrl
        self.netidMapperUrl = netidMapperUrl
        self.proxyAcsUrl = proxyAcsUrl
        self.proxyOidcRedirectUrl = proxyOidcRedirectUrl
        self.proxySamlAudienceOverride = proxySamlAudienceOverride
        self.proxyScimServerUrl = proxyScimServerUrl
        self.samlMapperUrl = samlMapperUrl
        self.scimMapperUrl = scimMapperUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appleMapperUrl = "apple_mapper_url"
        case auth0MapperUrl = "auth0_mapper_url"
        case customHostnameId = "custom_hostname_id"
        case enableScim = "enable_scim"
        case enableSso = "enable_sso"
        case expiresAt = "expires_at"
        case facebookMapperUrl = "facebook_mapper_url"
        case genericOidcMapperUrl = "generic_oidc_mapper_url"
        case githubMapperUrl = "github_mapper_url"
        case gitlabMapperUrl = "gitlab_mapper_url"
        case googleMapperUrl = "google_mapper_url"
        case microsoftMapperUrl = "microsoft_mapper_url"
        case netidMapperUrl = "netid_mapper_url"
        case proxyAcsUrl = "proxy_acs_url"
        case proxyOidcRedirectUrl = "proxy_oidc_redirect_url"
        case proxySamlAudienceOverride = "proxy_saml_audience_override"
        case proxyScimServerUrl = "proxy_scim_server_url"
        case samlMapperUrl = "saml_mapper_url"
        case scimMapperUrl = "scim_mapper_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appleMapperUrl, forKey: .appleMapperUrl)
        try container.encodeIfPresent(auth0MapperUrl, forKey: .auth0MapperUrl)
        try container.encodeIfPresent(customHostnameId, forKey: .customHostnameId)
        try container.encode(enableScim, forKey: .enableScim)
        try container.encode(enableSso, forKey: .enableSso)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(facebookMapperUrl, forKey: .facebookMapperUrl)
        try container.encodeIfPresent(genericOidcMapperUrl, forKey: .genericOidcMapperUrl)
        try container.encodeIfPresent(githubMapperUrl, forKey: .githubMapperUrl)
        try container.encodeIfPresent(gitlabMapperUrl, forKey: .gitlabMapperUrl)
        try container.encodeIfPresent(googleMapperUrl, forKey: .googleMapperUrl)
        try container.encodeIfPresent(microsoftMapperUrl, forKey: .microsoftMapperUrl)
        try container.encodeIfPresent(netidMapperUrl, forKey: .netidMapperUrl)
        try container.encodeIfPresent(proxyAcsUrl, forKey: .proxyAcsUrl)
        try container.encodeIfPresent(proxyOidcRedirectUrl, forKey: .proxyOidcRedirectUrl)
        try container.encodeIfPresent(proxySamlAudienceOverride, forKey: .proxySamlAudienceOverride)
        try container.encodeIfPresent(proxyScimServerUrl, forKey: .proxyScimServerUrl)
        try container.encodeIfPresent(samlMapperUrl, forKey: .samlMapperUrl)
        try container.encodeIfPresent(scimMapperUrl, forKey: .scimMapperUrl)
    }
}

