//
// DeviceUserAuthRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceUserAuthRequest: Sendable, Codable, Hashable {

    /** ID is the identifier (\"device challenge\") of the device grant request. It is used to identify the session. */
    public var challenge: String
    public var client: OAuth2Client?
    public var handledAt: Date?
    /** RequestURL is the original Device Authorization URL requested. */
    public var requestUrl: String?
    public var requestedAccessTokenAudience: [String]?
    public var requestedScope: [String]?

    public init(challenge: String, client: OAuth2Client? = nil, handledAt: Date? = nil, requestUrl: String? = nil, requestedAccessTokenAudience: [String]? = nil, requestedScope: [String]? = nil) {
        self.challenge = challenge
        self.client = client
        self.handledAt = handledAt
        self.requestUrl = requestUrl
        self.requestedAccessTokenAudience = requestedAccessTokenAudience
        self.requestedScope = requestedScope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case challenge
        case client
        case handledAt = "handled_at"
        case requestUrl = "request_url"
        case requestedAccessTokenAudience = "requested_access_token_audience"
        case requestedScope = "requested_scope"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(challenge, forKey: .challenge)
        try container.encodeIfPresent(client, forKey: .client)
        try container.encodeIfPresent(handledAt, forKey: .handledAt)
        try container.encodeIfPresent(requestUrl, forKey: .requestUrl)
        try container.encodeIfPresent(requestedAccessTokenAudience, forKey: .requestedAccessTokenAudience)
        try container.encodeIfPresent(requestedScope, forKey: .requestedScope)
    }
}

