//
// DeviceAuthorization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** # Ory&#39;s OAuth 2.0 Device Authorization API */
public struct DeviceAuthorization: Sendable, Codable, Hashable {

    /** The device verification code. */
    public var deviceCode: String?
    /** The lifetime in seconds of the \"device_code\" and \"user_code\". */
    public var expiresIn: Int64?
    /** The minimum amount of time in seconds that the client SHOULD wait between polling requests to the token endpoint.  If no value is provided, clients MUST use 5 as the default. */
    public var interval: Int64?
    /** The end-user verification code. */
    public var userCode: String?
    /** The end-user verification URI on the authorization server.  The URI should be short and easy to remember as end users will be asked to manually type it into their user agent. */
    public var verificationUri: String?
    /** A verification URI that includes the \"user_code\" (or other information with the same function as the \"user_code\"), which is designed for non-textual transmission. */
    public var verificationUriComplete: String?

    public init(deviceCode: String? = nil, expiresIn: Int64? = nil, interval: Int64? = nil, userCode: String? = nil, verificationUri: String? = nil, verificationUriComplete: String? = nil) {
        self.deviceCode = deviceCode
        self.expiresIn = expiresIn
        self.interval = interval
        self.userCode = userCode
        self.verificationUri = verificationUri
        self.verificationUriComplete = verificationUriComplete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceCode = "device_code"
        case expiresIn = "expires_in"
        case interval
        case userCode = "user_code"
        case verificationUri = "verification_uri"
        case verificationUriComplete = "verification_uri_complete"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceCode, forKey: .deviceCode)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(interval, forKey: .interval)
        try container.encodeIfPresent(userCode, forKey: .userCode)
        try container.encodeIfPresent(verificationUri, forKey: .verificationUri)
        try container.encodeIfPresent(verificationUriComplete, forKey: .verificationUriComplete)
    }
}

