//
// EmailTemplateDataBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmailTemplateDataBody: Sendable, Codable, Hashable {

    public var html: String
    public var plaintext: String

    public init(html: String, plaintext: String) {
        self.html = html
        self.plaintext = plaintext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case html
        case plaintext
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(html, forKey: .html)
        try container.encode(plaintext, forKey: .plaintext)
    }
}

