//
// EventStream.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Event Stream */
public struct EventStream: Sendable, Codable, Hashable {

    public var createdAt: Date?
    public var id: String?
    public var roleArn: String?
    public var topicArn: String?
    public var type: String?
    public var updatedAt: Date?

    public init(createdAt: Date? = nil, id: String? = nil, roleArn: String? = nil, topicArn: String? = nil, type: String? = nil, updatedAt: Date? = nil) {
        self.createdAt = createdAt
        self.id = id
        self.roleArn = roleArn
        self.topicArn = topicArn
        self.type = type
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case id
        case roleArn = "role_arn"
        case topicArn = "topic_arn"
        case type
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(roleArn, forKey: .roleArn)
        try container.encodeIfPresent(topicArn, forKey: .topicArn)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension EventStream: Identifiable {}
