//
// GetMetricsCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response of the getIdentityCount endpoint */
public struct GetMetricsCount: Sendable, Codable, Hashable {

    /** The total count */
    public var count: Int64
    /** Helper field to identify the service used for this response */
    public var serviceName: String

    public init(count: Int64, serviceName: String) {
        self.count = count
        self.serviceName = serviceName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case serviceName = "service_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(serviceName, forKey: .serviceName)
    }
}

