//
// GetProjectEvents.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response of the getProjectEvents endpoint */
public struct GetProjectEvents: Sendable, Codable, Hashable {

    /** The list of data points. */
    public var events: [ProjectEventsDatapoint]
    /** Pagination token to be included in next page request */
    public var pageToken: String?

    public init(events: [ProjectEventsDatapoint], pageToken: String? = nil) {
        self.events = events
        self.pageToken = pageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
        case pageToken = "page_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(events, forKey: .events)
        try container.encodeIfPresent(pageToken, forKey: .pageToken)
    }
}

