//
// GetSessionActivity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response of the getSessionActivity endpoint */
public struct GetSessionActivity: Sendable, Codable, Hashable {

    /** The list of data points. */
    public var data: [SessionActivityDatapoint]

    public init(data: [SessionActivityDatapoint]) {
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
    }
}

