//
// HealthNotReadyStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthNotReadyStatus: Sendable, Codable, Hashable {

    /** Errors contains a list of errors that caused the not ready status. */
    public var errors: [String: String]?

    public init(errors: [String: String]? = nil) {
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

