//
// IdentitySchemaPreset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IdentitySchemaPreset: Sendable, Codable, Hashable {

    /** Schema is the Identity JSON Schema */
    public var schema: JSONValue
    /** URL is the preset identifier */
    public var url: String

    public init(schema: JSONValue, url: String) {
        self.schema = schema
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schema
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schema, forKey: .schema)
        try container.encode(url, forKey: .url)
    }
}

