//
// IdentityWithCredentialsOidcConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IdentityWithCredentialsOidcConfig: Sendable, Codable, Hashable {

    /** A list of OpenID Connect Providers */
    public var providers: [IdentityWithCredentialsOidcConfigProvider]?

    public init(providers: [IdentityWithCredentialsOidcConfigProvider]? = nil) {
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providers, forKey: .providers)
    }
}

