//
// IdentityWithCredentialsSaml.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Payload to import SAML credentials */
public struct IdentityWithCredentialsSaml: Sendable, Codable, Hashable {

    public var config: IdentityWithCredentialsSamlConfig?

    public init(config: IdentityWithCredentialsSamlConfig? = nil) {
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

