//
// IdentityCredentialsCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** CredentialsCode represents a one time login/registration code */
public struct IdentityCredentialsCode: Sendable, Codable, Hashable {

    public var addresses: [IdentityCredentialsCodeAddress]?

    public init(addresses: [IdentityCredentialsCodeAddress]? = nil) {
        self.addresses = addresses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addresses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addresses, forKey: .addresses)
    }
}

