//
// IdentityWithCredentialsOidc.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Create Identity and Import Social Sign In Credentials */
public struct IdentityWithCredentialsOidc: Sendable, Codable, Hashable {

    public var config: IdentityWithCredentialsOidcConfig?

    public init(config: IdentityWithCredentialsOidcConfig? = nil) {
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

