//
// InvoiceDataV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InvoiceDataV1: Sendable, Codable, Hashable {

    public var billingPeriod: TimeInterval
    /** The currency of the invoice. */
    public var currency: String
    /** Deleted is true if the invoice has been soft-deleted. */
    public var deleted: Bool?
    /** The items that are part of this invoice. */
    public var items: [LineItemV1]
    /** The plan that this invoice is based on, in the format \"Name@version\". */
    public var plan: String?
    public var stripeInvoiceItem: String?
    /** The status of the invoice, one of `draft`, `open`, `paid`, `uncollectible`, or `void`. [Learn more](https://stripe.com/docs/billing/invoices/workflow#workflow-overview) */
    public var stripeInvoiceStatus: String?
    /** An optional link to the invoice on Stripe. */
    public var stripeLink: String?
    /** The subtitle of the invoice. */
    public var subtitle: String?
    public var tax: TaxLineItem?
    /** The title of the invoice. */
    public var title: String
    public var totalInCent: Int64

    public init(billingPeriod: TimeInterval, currency: String, deleted: Bool? = nil, items: [LineItemV1], plan: String? = nil, stripeInvoiceItem: String? = nil, stripeInvoiceStatus: String? = nil, stripeLink: String? = nil, subtitle: String? = nil, tax: TaxLineItem? = nil, title: String, totalInCent: Int64) {
        self.billingPeriod = billingPeriod
        self.currency = currency
        self.deleted = deleted
        self.items = items
        self.plan = plan
        self.stripeInvoiceItem = stripeInvoiceItem
        self.stripeInvoiceStatus = stripeInvoiceStatus
        self.stripeLink = stripeLink
        self.subtitle = subtitle
        self.tax = tax
        self.title = title
        self.totalInCent = totalInCent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case billingPeriod = "billing_period"
        case currency
        case deleted
        case items
        case plan
        case stripeInvoiceItem = "stripe_invoice_item"
        case stripeInvoiceStatus = "stripe_invoice_status"
        case stripeLink = "stripe_link"
        case subtitle
        case tax
        case title
        case totalInCent = "total_in_cent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(billingPeriod, forKey: .billingPeriod)
        try container.encode(currency, forKey: .currency)
        try container.encodeIfPresent(deleted, forKey: .deleted)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(stripeInvoiceItem, forKey: .stripeInvoiceItem)
        try container.encodeIfPresent(stripeInvoiceStatus, forKey: .stripeInvoiceStatus)
        try container.encodeIfPresent(stripeLink, forKey: .stripeLink)
        try container.encodeIfPresent(subtitle, forKey: .subtitle)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encode(title, forKey: .title)
        try container.encode(totalInCent, forKey: .totalInCent)
    }
}

