//
// LineItemV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LineItemV1: Sendable, Codable, Hashable {

    public var amountInCent: Int64?
    public var description: String?
    /** Each line item can have sub-items to create a hierarchy. */
    public var items: [LineItemV1]?
    public var quantity: Int64?
    public var title: String?
    public var unitPrice: String?

    public init(amountInCent: Int64? = nil, description: String? = nil, items: [LineItemV1]? = nil, quantity: Int64? = nil, title: String? = nil, unitPrice: String? = nil) {
        self.amountInCent = amountInCent
        self.description = description
        self.items = items
        self.quantity = quantity
        self.title = title
        self.unitPrice = unitPrice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountInCent = "amount_in_cent"
        case description
        case items
        case quantity
        case title
        case unitPrice = "unit_price"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amountInCent, forKey: .amountInCent)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(unitPrice, forKey: .unitPrice)
    }
}

