//
// ListEventStreams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Event Stream List */
public struct ListEventStreams: Sendable, Codable, Hashable {

    public var eventStreams: [EventStream]?

    public init(eventStreams: [EventStream]? = nil) {
        self.eventStreams = eventStreams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventStreams = "event_streams"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventStreams, forKey: .eventStreams)
    }
}

