//
// ListWorkspaceProjects.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListWorkspaceProjects: Sendable, Codable, Hashable {

    public var hasNextPage: Bool
    public var nextPage: String
    public var projects: [ProjectMetadata]

    public init(hasNextPage: Bool, nextPage: String, projects: [ProjectMetadata]) {
        self.hasNextPage = hasNextPage
        self.nextPage = nextPage
        self.projects = projects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasNextPage = "has_next_page"
        case nextPage = "next_page"
        case projects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hasNextPage, forKey: .hasNextPage)
        try container.encode(nextPage, forKey: .nextPage)
        try container.encode(projects, forKey: .projects)
    }
}

