//
// ListWorkspaces.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListWorkspaces: Sendable, Codable, Hashable {

    public var hasNextPage: Bool
    public var nextPageToken: String
    public var workspaces: [Workspace]

    public init(hasNextPage: Bool, nextPageToken: String, workspaces: [Workspace]) {
        self.hasNextPage = hasNextPage
        self.nextPageToken = nextPageToken
        self.workspaces = workspaces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasNextPage = "has_next_page"
        case nextPageToken = "next_page_token"
        case workspaces
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hasNextPage, forKey: .hasNextPage)
        try container.encode(nextPageToken, forKey: .nextPageToken)
        try container.encode(workspaces, forKey: .workspaces)
    }
}

