//
// Money.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Money: Sendable, Codable, Hashable {

    public var cents: Int64?
    public var string: String?
    public var unit: String?

    public init(cents: Int64? = nil, string: String? = nil, unit: String? = nil) {
        self.cents = cents
        self.string = string
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cents = "Cents"
        case string = "String"
        case unit = "Unit"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cents, forKey: .cents)
        try container.encodeIfPresent(string, forKey: .string)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

