//
// NormalizedProjectRevisionSAMLProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NormalizedProjectRevisionSAMLProvider: Sendable, Codable, Hashable {

    public enum State: String, Sendable, Codable, CaseIterable {
        case enabled = "enabled"
        case disabled = "disabled"
    }
    public var audienceOverrideBaseUrl: String?
    /** The Project's Revision Creation Date */
    public var createdAt: Date?
    public var id: String?
    /** Label represents an optional label which can be used in the UI generation. */
    public var label: String?
    /** Mapper specifies the JSONNet code snippet which uses the OpenID Connect Provider's data (e.g. GitHub or Google profile information) to hydrate the identity's data. */
    public var mapperUrl: String?
    public var organizationId: String?
    /** The Revision's ID this schema belongs to */
    public var projectRevisionId: String?
    /** ID is the provider's ID */
    public var providerId: String?
    public var proxyAcsUrl: String?
    public var proxySamlAudienceOverride: String?
    /** RawIDPMetadataXML is the raw XML metadata of the IDP. */
    public var rawIdpMetadataXml: String?
    /** State indicates the state of the provider  Only providers with state `enabled` will be used for authentication enabled ThirdPartyProviderStateEnabled disabled ThirdPartyProviderStateDisabled */
    public var state: State?
    /** Last Time Project's Revision was Updated */
    public var updatedAt: Date?

    public init(audienceOverrideBaseUrl: String? = nil, createdAt: Date? = nil, id: String? = nil, label: String? = nil, mapperUrl: String? = nil, organizationId: String? = nil, projectRevisionId: String? = nil, providerId: String? = nil, proxyAcsUrl: String? = nil, proxySamlAudienceOverride: String? = nil, rawIdpMetadataXml: String? = nil, state: State? = nil, updatedAt: Date? = nil) {
        self.audienceOverrideBaseUrl = audienceOverrideBaseUrl
        self.createdAt = createdAt
        self.id = id
        self.label = label
        self.mapperUrl = mapperUrl
        self.organizationId = organizationId
        self.projectRevisionId = projectRevisionId
        self.providerId = providerId
        self.proxyAcsUrl = proxyAcsUrl
        self.proxySamlAudienceOverride = proxySamlAudienceOverride
        self.rawIdpMetadataXml = rawIdpMetadataXml
        self.state = state
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audienceOverrideBaseUrl = "audience_override_base_url"
        case createdAt = "created_at"
        case id
        case label
        case mapperUrl = "mapper_url"
        case organizationId = "organization_id"
        case projectRevisionId = "project_revision_id"
        case providerId = "provider_id"
        case proxyAcsUrl = "proxy_acs_url"
        case proxySamlAudienceOverride = "proxy_saml_audience_override"
        case rawIdpMetadataXml = "raw_idp_metadata_xml"
        case state
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(audienceOverrideBaseUrl, forKey: .audienceOverrideBaseUrl)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(mapperUrl, forKey: .mapperUrl)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(projectRevisionId, forKey: .projectRevisionId)
        try container.encodeIfPresent(providerId, forKey: .providerId)
        try container.encodeIfPresent(proxyAcsUrl, forKey: .proxyAcsUrl)
        try container.encodeIfPresent(proxySamlAudienceOverride, forKey: .proxySamlAudienceOverride)
        try container.encodeIfPresent(rawIdpMetadataXml, forKey: .rawIdpMetadataXml)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension NormalizedProjectRevisionSAMLProvider: Identifiable {}
