//
// OnboardingPortalOrganization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OnboardingPortalOrganization: Sendable, Codable, Hashable {

    /** AppleMapper specifies the JSONNet code snippet which uses Apple's profile information to hydrate the identity's data. */
    public var appleMapperUrl: String?
    /** Auth0Mapper specifies the JSONNet code snippet which uses Auth0's profile information to hydrate the identity's data. */
    public var auth0MapperUrl: String?
    public var baseUrl: String
    /** FacebookMapper specifies the JSONNet code snippet which uses Facebook's profile information to hydrate the identity's data. */
    public var facebookMapperUrl: String?
    /** GenericOIDCMapper specifies the JSONNet code snippet which uses the OIDC Provider's profile information to hydrate the identity's data. */
    public var genericOidcMapperUrl: String?
    /** GithubMapper specifies the JSONNet code snippet which uses GitHub's profile information to hydrate the identity's data. */
    public var githubMapperUrl: String?
    /** GitLabMapper specifies the JSONNet code snippet which uses GitLab's profile information to hydrate the identity's data. */
    public var gitlabMapperUrl: String?
    /** GoogleMapper specifies the JSONNet code snippet which uses Google's profile information to hydrate the identity's data. */
    public var googleMapperUrl: String?
    public var kratosSelfserviceMethodsOidcConfigProviders: [NormalizedProjectRevisionThirdPartyProvider]
    public var kratosSelfserviceMethodsSamlConfigProviders: [NormalizedProjectRevisionSAMLProvider]
    /** MicrosoftMapper specifies the JSONNet code snippet which uses Microsoft's profile information to hydrate the identity's data. */
    public var microsoftMapperUrl: String?
    /** NetIDMapper specifies the JSONNet code snippet which uses NetID's profile information to hydrate the identity's data. */
    public var netidMapperUrl: String?
    public var oidcSsoEnabled: Bool?
    public var organizationId: String
    /** Organization Label */
    public var organizationLabel: String?
    /** Proxy ACS URL if overriding with a customer-controlled URL */
    public var proxyAcsUrl: String?
    /** Proxy OIDC Redirect URL if overriding with a customer-controlled URL */
    public var proxyOidcRedirectUrl: String?
    /** SAML Audience Override if overriding with a customer-controlled one */
    public var proxySamlAudienceOverride: String?
    /** Proxy SCIM Server URL if overriding with a customer-controlled URL */
    public var proxyScimServerUrl: String?
    public var revisionId: String
    /** SAMLMapper specifies the JSONNet code snippet which uses the SAML Provider's profile information to hydrate the identity's data. */
    public var samlMapperUrl: String?
    public var samlSsoEnabled: Bool?
    public var scimClients: [NormalizedProjectRevisionScimClient]
    public var scimEnabled: Bool
    /** SCIMMapper specifies the JSONNet code snippet which uses the SCIM Provider's profile information to hydrate the identity's data. */
    public var scimMapperUrl: String?
    public var ssoEnabled: Bool

    public init(appleMapperUrl: String? = nil, auth0MapperUrl: String? = nil, baseUrl: String, facebookMapperUrl: String? = nil, genericOidcMapperUrl: String? = nil, githubMapperUrl: String? = nil, gitlabMapperUrl: String? = nil, googleMapperUrl: String? = nil, kratosSelfserviceMethodsOidcConfigProviders: [NormalizedProjectRevisionThirdPartyProvider], kratosSelfserviceMethodsSamlConfigProviders: [NormalizedProjectRevisionSAMLProvider], microsoftMapperUrl: String? = nil, netidMapperUrl: String? = nil, oidcSsoEnabled: Bool? = nil, organizationId: String, organizationLabel: String? = nil, proxyAcsUrl: String? = nil, proxyOidcRedirectUrl: String? = nil, proxySamlAudienceOverride: String? = nil, proxyScimServerUrl: String? = nil, revisionId: String, samlMapperUrl: String? = nil, samlSsoEnabled: Bool? = nil, scimClients: [NormalizedProjectRevisionScimClient], scimEnabled: Bool, scimMapperUrl: String? = nil, ssoEnabled: Bool) {
        self.appleMapperUrl = appleMapperUrl
        self.auth0MapperUrl = auth0MapperUrl
        self.baseUrl = baseUrl
        self.facebookMapperUrl = facebookMapperUrl
        self.genericOidcMapperUrl = genericOidcMapperUrl
        self.githubMapperUrl = githubMapperUrl
        self.gitlabMapperUrl = gitlabMapperUrl
        self.googleMapperUrl = googleMapperUrl
        self.kratosSelfserviceMethodsOidcConfigProviders = kratosSelfserviceMethodsOidcConfigProviders
        self.kratosSelfserviceMethodsSamlConfigProviders = kratosSelfserviceMethodsSamlConfigProviders
        self.microsoftMapperUrl = microsoftMapperUrl
        self.netidMapperUrl = netidMapperUrl
        self.oidcSsoEnabled = oidcSsoEnabled
        self.organizationId = organizationId
        self.organizationLabel = organizationLabel
        self.proxyAcsUrl = proxyAcsUrl
        self.proxyOidcRedirectUrl = proxyOidcRedirectUrl
        self.proxySamlAudienceOverride = proxySamlAudienceOverride
        self.proxyScimServerUrl = proxyScimServerUrl
        self.revisionId = revisionId
        self.samlMapperUrl = samlMapperUrl
        self.samlSsoEnabled = samlSsoEnabled
        self.scimClients = scimClients
        self.scimEnabled = scimEnabled
        self.scimMapperUrl = scimMapperUrl
        self.ssoEnabled = ssoEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appleMapperUrl = "apple_mapper_url"
        case auth0MapperUrl = "auth0_mapper_url"
        case baseUrl = "base_url"
        case facebookMapperUrl = "facebook_mapper_url"
        case genericOidcMapperUrl = "generic_oidc_mapper_url"
        case githubMapperUrl = "github_mapper_url"
        case gitlabMapperUrl = "gitlab_mapper_url"
        case googleMapperUrl = "google_mapper_url"
        case kratosSelfserviceMethodsOidcConfigProviders = "kratos_selfservice_methods_oidc_config_providers"
        case kratosSelfserviceMethodsSamlConfigProviders = "kratos_selfservice_methods_saml_config_providers"
        case microsoftMapperUrl = "microsoft_mapper_url"
        case netidMapperUrl = "netid_mapper_url"
        case oidcSsoEnabled = "oidc_sso_enabled"
        case organizationId = "organization_id"
        case organizationLabel = "organization_label"
        case proxyAcsUrl = "proxy_acs_url"
        case proxyOidcRedirectUrl = "proxy_oidc_redirect_url"
        case proxySamlAudienceOverride = "proxy_saml_audience_override"
        case proxyScimServerUrl = "proxy_scim_server_url"
        case revisionId = "revision_id"
        case samlMapperUrl = "saml_mapper_url"
        case samlSsoEnabled = "saml_sso_enabled"
        case scimClients = "scim_clients"
        case scimEnabled = "scim_enabled"
        case scimMapperUrl = "scim_mapper_url"
        case ssoEnabled = "sso_enabled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appleMapperUrl, forKey: .appleMapperUrl)
        try container.encodeIfPresent(auth0MapperUrl, forKey: .auth0MapperUrl)
        try container.encode(baseUrl, forKey: .baseUrl)
        try container.encodeIfPresent(facebookMapperUrl, forKey: .facebookMapperUrl)
        try container.encodeIfPresent(genericOidcMapperUrl, forKey: .genericOidcMapperUrl)
        try container.encodeIfPresent(githubMapperUrl, forKey: .githubMapperUrl)
        try container.encodeIfPresent(gitlabMapperUrl, forKey: .gitlabMapperUrl)
        try container.encodeIfPresent(googleMapperUrl, forKey: .googleMapperUrl)
        try container.encode(kratosSelfserviceMethodsOidcConfigProviders, forKey: .kratosSelfserviceMethodsOidcConfigProviders)
        try container.encode(kratosSelfserviceMethodsSamlConfigProviders, forKey: .kratosSelfserviceMethodsSamlConfigProviders)
        try container.encodeIfPresent(microsoftMapperUrl, forKey: .microsoftMapperUrl)
        try container.encodeIfPresent(netidMapperUrl, forKey: .netidMapperUrl)
        try container.encodeIfPresent(oidcSsoEnabled, forKey: .oidcSsoEnabled)
        try container.encode(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(organizationLabel, forKey: .organizationLabel)
        try container.encodeIfPresent(proxyAcsUrl, forKey: .proxyAcsUrl)
        try container.encodeIfPresent(proxyOidcRedirectUrl, forKey: .proxyOidcRedirectUrl)
        try container.encodeIfPresent(proxySamlAudienceOverride, forKey: .proxySamlAudienceOverride)
        try container.encodeIfPresent(proxyScimServerUrl, forKey: .proxyScimServerUrl)
        try container.encode(revisionId, forKey: .revisionId)
        try container.encodeIfPresent(samlMapperUrl, forKey: .samlMapperUrl)
        try container.encodeIfPresent(samlSsoEnabled, forKey: .samlSsoEnabled)
        try container.encode(scimClients, forKey: .scimClients)
        try container.encode(scimEnabled, forKey: .scimEnabled)
        try container.encodeIfPresent(scimMapperUrl, forKey: .scimMapperUrl)
        try container.encode(ssoEnabled, forKey: .ssoEnabled)
    }
}

