//
// OrganizationOnboardingPortalLinksResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrganizationOnboardingPortalLinksResponse: Sendable, Codable, Hashable {

    public var links: [OnboardingPortalLink]

    public init(links: [OnboardingPortalLink]) {
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(links, forKey: .links)
    }
}

