//
// PermissionsOnWorkspace.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Get Permissions on Project Request Parameters */
public struct PermissionsOnWorkspace: Sendable, Codable, Hashable {

    public var permissions: [String: Bool]?

    public init(permissions: [String: Bool]? = nil) {
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}

