//
// PlanDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanDetails: Sendable, Codable, Hashable {

    /** BaseFeeMonthly is the monthly base fee for the plan. */
    public var baseFeeMonthly: Int64
    /** BaseFeeYearly is the yearly base fee for the plan. */
    public var baseFeeYearly: Int64
    /** Custom is true if the plan is custom. This means it will be hidden from the pricing page. */
    public var custom: Bool
    /** Description is the description of the plan. */
    public var description: String
    public var developmentFeatures: [String: GenericUsage]
    public var features: [String: GenericUsage]
    /** Latest is true if the plan is the latest version of a plan and should be available for self-service usage. */
    public var latest: Bool?
    /** Name is the name of the plan. */
    public var name: String
    public var productionFeatures: [String: GenericUsage]
    public var stagingFeatures: [String: GenericUsage]
    /** Version is the version of the plan. The combination of `name@version` must be unique. */
    public var version: Int64

    public init(baseFeeMonthly: Int64, baseFeeYearly: Int64, custom: Bool, description: String, developmentFeatures: [String: GenericUsage], features: [String: GenericUsage], latest: Bool? = nil, name: String, productionFeatures: [String: GenericUsage], stagingFeatures: [String: GenericUsage], version: Int64) {
        self.baseFeeMonthly = baseFeeMonthly
        self.baseFeeYearly = baseFeeYearly
        self.custom = custom
        self.description = description
        self.developmentFeatures = developmentFeatures
        self.features = features
        self.latest = latest
        self.name = name
        self.productionFeatures = productionFeatures
        self.stagingFeatures = stagingFeatures
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case baseFeeMonthly = "base_fee_monthly"
        case baseFeeYearly = "base_fee_yearly"
        case custom
        case description
        case developmentFeatures = "development_features"
        case features
        case latest
        case name
        case productionFeatures = "production_features"
        case stagingFeatures = "staging_features"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(baseFeeMonthly, forKey: .baseFeeMonthly)
        try container.encode(baseFeeYearly, forKey: .baseFeeYearly)
        try container.encode(custom, forKey: .custom)
        try container.encode(description, forKey: .description)
        try container.encode(developmentFeatures, forKey: .developmentFeatures)
        try container.encode(features, forKey: .features)
        try container.encodeIfPresent(latest, forKey: .latest)
        try container.encode(name, forKey: .name)
        try container.encode(productionFeatures, forKey: .productionFeatures)
        try container.encode(stagingFeatures, forKey: .stagingFeatures)
        try container.encode(version, forKey: .version)
    }
}

