//
// ProjectMember.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectMember: Sendable, Codable, Hashable {

    public var email: String
    public var emailVerified: Bool
    public var id: String
    public var name: String
    public var role: String

    public init(email: String, emailVerified: Bool, id: String, name: String, role: String) {
        self.email = email
        self.emailVerified = emailVerified
        self.id = id
        self.name = name
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case emailVerified = "email_verified"
        case id
        case name
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(emailVerified, forKey: .emailVerified)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(role, forKey: .role)
    }
}


extension ProjectMember: Identifiable {}
