//
// ProjectHost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectHost: Sendable, Codable, Hashable {

    /** The project's host. */
    public var host: String
    /** The mapping's ID. */
    public var id: String
    /** The Revision's Project ID */
    public var projectId: String

    public init(host: String, id: String, projectId: String) {
        self.host = host
        self.id = id
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case host
        case id
        case projectId = "project_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(host, forKey: .host)
        try container.encode(id, forKey: .id)
        try container.encode(projectId, forKey: .projectId)
    }
}


extension ProjectHost: Identifiable {}
