//
// Project.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Project: Sendable, Codable, Hashable {

    public enum Environment: String, Sendable, Codable, CaseIterable {
        case prod = "prod"
        case stage = "stage"
        case dev = "dev"
    }
    public enum HomeRegion: String, Sendable, Codable, CaseIterable {
        case euCentral = "eu-central"
        case asiaNortheast = "asia-northeast"
        case usEast = "us-east"
        case usWest = "us-west"
        case us = "us"
        case global = "global"
    }
    public enum State: String, Sendable, Codable, CaseIterable {
        case running = "running"
        case halted = "halted"
        case deleted = "deleted"
    }
    public var corsAdmin: ProjectCors?
    public var corsPublic: ProjectCors?
    /** The environment of the project. prod Production stage Staging dev Development */
    public var environment: Environment
    /** The project home region.  This is used to set where the project data is stored and where the project's endpoints are located. eu-central EUCentral asia-northeast AsiaNorthEast us-east USEast us-west USWest us US global Global */
    public var homeRegion: HomeRegion
    /** The project's ID. */
    public var id: String
    /** The name of the project. */
    public var name: String
    /** The organizations of the project.  Organizations are used to group users and enforce certain restrictions like usage of SSO. */
    public var organizations: [BasicOrganization]
    /** The configuration revision ID. */
    public var revisionId: String
    public var services: ProjectServices
    /** The project's slug */
    public var slug: String
    /** The state of the project. running Running halted Halted deleted Deleted */
    public var state: State
    public var workspaceId: String?

    public init(corsAdmin: ProjectCors? = nil, corsPublic: ProjectCors? = nil, environment: Environment, homeRegion: HomeRegion, id: String, name: String, organizations: [BasicOrganization], revisionId: String, services: ProjectServices, slug: String, state: State, workspaceId: String? = nil) {
        self.corsAdmin = corsAdmin
        self.corsPublic = corsPublic
        self.environment = environment
        self.homeRegion = homeRegion
        self.id = id
        self.name = name
        self.organizations = organizations
        self.revisionId = revisionId
        self.services = services
        self.slug = slug
        self.state = state
        self.workspaceId = workspaceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case corsAdmin = "cors_admin"
        case corsPublic = "cors_public"
        case environment
        case homeRegion = "home_region"
        case id
        case name
        case organizations
        case revisionId = "revision_id"
        case services
        case slug
        case state
        case workspaceId = "workspace_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(corsAdmin, forKey: .corsAdmin)
        try container.encodeIfPresent(corsPublic, forKey: .corsPublic)
        try container.encode(environment, forKey: .environment)
        try container.encode(homeRegion, forKey: .homeRegion)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(organizations, forKey: .organizations)
        try container.encode(revisionId, forKey: .revisionId)
        try container.encode(services, forKey: .services)
        try container.encode(slug, forKey: .slug)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
    }
}


extension Project: Identifiable {}
