//
// ProjectEventsDatapoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProjectEventsDatapoint: Sendable, Codable, Hashable {

    /** Event attributes with details */
    public var attributes: [Attribute]
    /** Name of the event */
    public var name: String
    /** Time of occurence */
    public var timestamp: Date

    public init(attributes: [Attribute], name: String, timestamp: Date) {
        self.attributes = attributes
        self.name = name
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
        case name
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attributes, forKey: .attributes)
        try container.encode(name, forKey: .name)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

