//
// RecoveryFlowState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The experimental state represents the state of a recovery flow. This field is EXPERIMENTAL and subject to change! */
public enum RecoveryFlowState: String, Sendable, Codable, CaseIterable {
    case chooseMethod = "choose_method"
    case sentEmail = "sent_email"
    case passedChallenge = "passed_challenge"
}
