//
// RelationshipNamespaces.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Relationship Namespace List */
public struct RelationshipNamespaces: Sendable, Codable, Hashable {

    public var namespaces: [Namespace]?

    public init(namespaces: [Namespace]? = nil) {
        self.namespaces = namespaces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespaces
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(namespaces, forKey: .namespaces)
    }
}

