//
// RevisionAccountExperienceCustomTranslation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RevisionAccountExperienceCustomTranslation: Sendable, Codable, Hashable {

    /** The locale (e.g. \"en\", \"de\") */
    public var locale: String
    /** The URL where the i18n json can be found */
    public var translations: String

    public init(locale: String, translations: String) {
        self.locale = locale
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locale, forKey: .locale)
        try container.encode(translations, forKey: .translations)
    }
}

