//
// SchemaPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SchemaPatch: Sendable, Codable, Hashable {

    /** The json schema */
    public var data: JSONValue
    /** The user defined schema name */
    public var name: String

    public init(data: JSONValue, name: String) {
        self.data = data
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(name, forKey: .name)
    }
}

