//
// SessionActivityDatapoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SessionActivityDatapoint: Sendable, Codable, Hashable {

    /** Country of the events */
    public var country: String
    /** Number of events that failed in the given timeframe */
    public var failed: Int64
    /** Number of events that succeeded in the given timeframe */
    public var succeeded: Int64

    public init(country: String, failed: Int64, succeeded: Int64) {
        self.country = country
        self.failed = failed
        self.succeeded = succeeded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case failed
        case succeeded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(country, forKey: .country)
        try container.encode(failed, forKey: .failed)
        try container.encode(succeeded, forKey: .succeeded)
    }
}

