//
// SetEventStreamBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Event Stream Body */
public struct SetEventStreamBody: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case sns = "sns"
    }
    /** The AWS IAM role ARN to assume when publishing to the SNS topic. */
    public var roleArn: String
    /** The AWS SNS topic ARN. */
    public var topicArn: String
    /** The type of the event stream (AWS SNS, GCP Pub/Sub, etc). */
    public var type: ModelType

    public init(roleArn: String, topicArn: String, type: ModelType) {
        self.roleArn = roleArn
        self.topicArn = topicArn
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleArn = "role_arn"
        case topicArn = "topic_arn"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(roleArn, forKey: .roleArn)
        try container.encode(topicArn, forKey: .topicArn)
        try container.encode(type, forKey: .type)
    }
}

