//
// SetProjectBrandingThemeBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetProjectBrandingThemeBody: Sendable, Codable, Hashable {

    /** Favicon Type */
    public var faviconType: String?
    /** Favicon URL */
    public var faviconUrl: String?
    /** Logo type */
    public var logoType: String?
    /** Logo URL */
    public var logoUrl: String?
    /** Branding name */
    public var name: String?
    public var theme: ProjectBrandingColors?

    public init(faviconType: String? = nil, faviconUrl: String? = nil, logoType: String? = nil, logoUrl: String? = nil, name: String? = nil, theme: ProjectBrandingColors? = nil) {
        self.faviconType = faviconType
        self.faviconUrl = faviconUrl
        self.logoType = logoType
        self.logoUrl = logoUrl
        self.name = name
        self.theme = theme
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case faviconType = "favicon_type"
        case faviconUrl = "favicon_url"
        case logoType = "logo_type"
        case logoUrl = "logo_url"
        case name
        case theme
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(faviconType, forKey: .faviconType)
        try container.encodeIfPresent(faviconUrl, forKey: .faviconUrl)
        try container.encodeIfPresent(logoType, forKey: .logoType)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(theme, forKey: .theme)
    }
}

