//
// SettingsFlowState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The experimental state represents the state of a settings flow. This field is EXPERIMENTAL and subject to change! */
public enum SettingsFlowState: String, Sendable, Codable, CaseIterable {
    case showForm = "show_form"
    case success = "success"
}
