//
// Subscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Subscription: Sendable, Codable, Hashable {

    public enum Currency: String, Sendable, Codable, CaseIterable {
        case usd = "usd"
        case eur = "eur"
    }
    public enum CurrentInterval: String, Sendable, Codable, CaseIterable {
        case monthly = "monthly"
        case yearly = "yearly"
    }
    public var createdAt: Date
    /** The currency of the subscription. To change this, a new subscription must be created. usd USD eur Euro */
    public var currency: Currency
    /** The currently active interval of the subscription monthly Monthly yearly Yearly */
    public var currentInterval: CurrentInterval
    /** The currently active plan of the subscription */
    public var currentPlan: String
    public var currentPlanDetails: PlanDetails?
    /** The ID of the stripe customer */
    public var customerId: String
    /** The ID of the subscription */
    public var id: String
    public var intervalChangesTo: String?
    public var ongoingStripeCheckoutId: String?
    /** Until when the subscription is payed */
    public var payedUntil: Date
    public var planChangesAt: Date?
    public var planChangesTo: String?
    /** For `collection_method=charge_automatically` a subscription moves into `incomplete` if the initial payment attempt fails. A subscription in this status can only have metadata and default_source updated. Once the first invoice is paid, the subscription moves into an `active` status. If the first invoice is not paid within 23 hours, the subscription transitions to `incomplete_expired`. This is a terminal status, the open invoice will be voided and no further invoices will be generated.  A subscription that is currently in a trial period is `trialing` and moves to `active` when the trial period is over.  A subscription can only enter a `paused` status [when a trial ends without a payment method](https://stripe.com/billing/subscriptions/trials#create-free-trials-without-payment). A `paused` subscription doesn't generate invoices and can be resumed after your customer adds their payment method. The `paused` status is different from [pausing collection](https://stripe.com/billing/subscriptions/pause-payment), which still generates invoices and leaves the subscription's status unchanged.  If subscription `collection_method=charge_automatically`, it becomes `past_due` when payment is required but cannot be paid (due to failed payment or awaiting additional user actions). Once Stripe has exhausted all payment retry attempts, the subscription will become `canceled` or `unpaid` (depending on your subscriptions settings).  If subscription `collection_method=send_invoice` it becomes `past_due` when its invoice is not paid by the due date, and `canceled` or `unpaid` if it is still not paid by an additional deadline after that. Note that when a subscription has a status of `unpaid`, no subsequent invoices will be attempted (invoices will be created, but then immediately automatically closed). After receiving updated payment information from a customer, you may choose to reopen and pay their closed invoices. */
    public var status: String
    public var stripeCheckoutExpiresAt: Date?
    public var updatedAt: Date

    public init(createdAt: Date, currency: Currency, currentInterval: CurrentInterval, currentPlan: String, currentPlanDetails: PlanDetails? = nil, customerId: String, id: String, intervalChangesTo: String?, ongoingStripeCheckoutId: String? = nil, payedUntil: Date, planChangesAt: Date? = nil, planChangesTo: String?, status: String, stripeCheckoutExpiresAt: Date? = nil, updatedAt: Date) {
        self.createdAt = createdAt
        self.currency = currency
        self.currentInterval = currentInterval
        self.currentPlan = currentPlan
        self.currentPlanDetails = currentPlanDetails
        self.customerId = customerId
        self.id = id
        self.intervalChangesTo = intervalChangesTo
        self.ongoingStripeCheckoutId = ongoingStripeCheckoutId
        self.payedUntil = payedUntil
        self.planChangesAt = planChangesAt
        self.planChangesTo = planChangesTo
        self.status = status
        self.stripeCheckoutExpiresAt = stripeCheckoutExpiresAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case currency
        case currentInterval = "current_interval"
        case currentPlan = "current_plan"
        case currentPlanDetails = "current_plan_details"
        case customerId = "customer_id"
        case id
        case intervalChangesTo = "interval_changes_to"
        case ongoingStripeCheckoutId = "ongoing_stripe_checkout_id"
        case payedUntil = "payed_until"
        case planChangesAt = "plan_changes_at"
        case planChangesTo = "plan_changes_to"
        case status
        case stripeCheckoutExpiresAt = "stripe_checkout_expires_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(currency, forKey: .currency)
        try container.encode(currentInterval, forKey: .currentInterval)
        try container.encode(currentPlan, forKey: .currentPlan)
        try container.encodeIfPresent(currentPlanDetails, forKey: .currentPlanDetails)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(id, forKey: .id)
        try container.encode(intervalChangesTo, forKey: .intervalChangesTo)
        try container.encodeIfPresent(ongoingStripeCheckoutId, forKey: .ongoingStripeCheckoutId)
        try container.encode(payedUntil, forKey: .payedUntil)
        try container.encodeIfPresent(planChangesAt, forKey: .planChangesAt)
        try container.encode(planChangesTo, forKey: .planChangesTo)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(stripeCheckoutExpiresAt, forKey: .stripeCheckoutExpiresAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension Subscription: Identifiable {}
