//
// UiNodeAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UiNodeAttributes: Sendable, Codable, Hashable {
    case typeUiNodeAnchorAttributes(UiNodeAnchorAttributes)
    case typeUiNodeDivisionAttributes(UiNodeDivisionAttributes)
    case typeUiNodeImageAttributes(UiNodeImageAttributes)
    case typeUiNodeInputAttributes(UiNodeInputAttributes)
    case typeUiNodeScriptAttributes(UiNodeScriptAttributes)
    case typeUiNodeTextAttributes(UiNodeTextAttributes)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUiNodeAnchorAttributes(let value):
            try container.encode(value)
        case .typeUiNodeDivisionAttributes(let value):
            try container.encode(value)
        case .typeUiNodeImageAttributes(let value):
            try container.encode(value)
        case .typeUiNodeInputAttributes(let value):
            try container.encode(value)
        case .typeUiNodeScriptAttributes(let value):
            try container.encode(value)
        case .typeUiNodeTextAttributes(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case nodeType = "node_type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .nodeType)

        switch discriminatorValue {
        case "a":
            self = .typeUiNodeAnchorAttributes(try UiNodeAnchorAttributes(from: decoder))
        case "div":
            self = .typeUiNodeDivisionAttributes(try UiNodeDivisionAttributes(from: decoder))
        case "img":
            self = .typeUiNodeImageAttributes(try UiNodeImageAttributes(from: decoder))
        case "input":
            self = .typeUiNodeInputAttributes(try UiNodeInputAttributes(from: decoder))
        case "script":
            self = .typeUiNodeScriptAttributes(try UiNodeScriptAttributes(from: decoder))
        case "text":
            self = .typeUiNodeTextAttributes(try UiNodeTextAttributes(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UiNodeAttributes"
                )
            )
        }
    }
}


extension UiNodeAttributes: Identifiable {
    public var id: Self {
        self
    }
}
