//
// UpdateSettingsFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Settings Flow Request Body */
public enum UpdateSettingsFlowBody: Sendable, Codable, Hashable {
    case typeUpdateSettingsFlowWithLookupMethod(UpdateSettingsFlowWithLookupMethod)
    case typeUpdateSettingsFlowWithOidcMethod(UpdateSettingsFlowWithOidcMethod)
    case typeUpdateSettingsFlowWithPasskeyMethod(UpdateSettingsFlowWithPasskeyMethod)
    case typeUpdateSettingsFlowWithPasswordMethod(UpdateSettingsFlowWithPasswordMethod)
    case typeUpdateSettingsFlowWithProfileMethod(UpdateSettingsFlowWithProfileMethod)
    case typeUpdateSettingsFlowWithSamlMethod(UpdateSettingsFlowWithSamlMethod)
    case typeUpdateSettingsFlowWithTotpMethod(UpdateSettingsFlowWithTotpMethod)
    case typeUpdateSettingsFlowWithWebAuthnMethod(UpdateSettingsFlowWithWebAuthnMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateSettingsFlowWithLookupMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithOidcMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithPasskeyMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithPasswordMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithProfileMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithSamlMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithTotpMethod(let value):
            try container.encode(value)
        case .typeUpdateSettingsFlowWithWebAuthnMethod(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case method = "method"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .method)

        switch discriminatorValue {
        case "lookup_secret":
            self = .typeUpdateSettingsFlowWithLookupMethod(try UpdateSettingsFlowWithLookupMethod(from: decoder))
        case "oidc":
            self = .typeUpdateSettingsFlowWithOidcMethod(try UpdateSettingsFlowWithOidcMethod(from: decoder))
        case "passkey":
            self = .typeUpdateSettingsFlowWithPasskeyMethod(try UpdateSettingsFlowWithPasskeyMethod(from: decoder))
        case "password":
            self = .typeUpdateSettingsFlowWithPasswordMethod(try UpdateSettingsFlowWithPasswordMethod(from: decoder))
        case "profile":
            self = .typeUpdateSettingsFlowWithProfileMethod(try UpdateSettingsFlowWithProfileMethod(from: decoder))
        case "saml":
            self = .typeUpdateSettingsFlowWithSamlMethod(try UpdateSettingsFlowWithSamlMethod(from: decoder))
        case "totp":
            self = .typeUpdateSettingsFlowWithTotpMethod(try UpdateSettingsFlowWithTotpMethod(from: decoder))
        case "webauthn":
            self = .typeUpdateSettingsFlowWithWebAuthnMethod(try UpdateSettingsFlowWithWebAuthnMethod(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UpdateSettingsFlowBody"
                )
            )
        }
    }
}

