//
// UpdateLoginFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UpdateLoginFlowBody: Sendable, Codable, Hashable {
    case typeUpdateLoginFlowWithCodeMethod(UpdateLoginFlowWithCodeMethod)
    case typeUpdateLoginFlowWithIdentifierFirstMethod(UpdateLoginFlowWithIdentifierFirstMethod)
    case typeUpdateLoginFlowWithLookupSecretMethod(UpdateLoginFlowWithLookupSecretMethod)
    case typeUpdateLoginFlowWithOidcMethod(UpdateLoginFlowWithOidcMethod)
    case typeUpdateLoginFlowWithPasskeyMethod(UpdateLoginFlowWithPasskeyMethod)
    case typeUpdateLoginFlowWithPasswordMethod(UpdateLoginFlowWithPasswordMethod)
    case typeUpdateLoginFlowWithSamlMethod(UpdateLoginFlowWithSamlMethod)
    case typeUpdateLoginFlowWithTotpMethod(UpdateLoginFlowWithTotpMethod)
    case typeUpdateLoginFlowWithWebAuthnMethod(UpdateLoginFlowWithWebAuthnMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateLoginFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithIdentifierFirstMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithLookupSecretMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithOidcMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithPasskeyMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithPasswordMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithSamlMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithTotpMethod(let value):
            try container.encode(value)
        case .typeUpdateLoginFlowWithWebAuthnMethod(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case method = "method"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .method)

        switch discriminatorValue {
        case "code":
            self = .typeUpdateLoginFlowWithCodeMethod(try UpdateLoginFlowWithCodeMethod(from: decoder))
        case "identifier_first":
            self = .typeUpdateLoginFlowWithIdentifierFirstMethod(try UpdateLoginFlowWithIdentifierFirstMethod(from: decoder))
        case "lookup_secret":
            self = .typeUpdateLoginFlowWithLookupSecretMethod(try UpdateLoginFlowWithLookupSecretMethod(from: decoder))
        case "oidc":
            self = .typeUpdateLoginFlowWithOidcMethod(try UpdateLoginFlowWithOidcMethod(from: decoder))
        case "passkey":
            self = .typeUpdateLoginFlowWithPasskeyMethod(try UpdateLoginFlowWithPasskeyMethod(from: decoder))
        case "password":
            self = .typeUpdateLoginFlowWithPasswordMethod(try UpdateLoginFlowWithPasswordMethod(from: decoder))
        case "saml":
            self = .typeUpdateLoginFlowWithSamlMethod(try UpdateLoginFlowWithSamlMethod(from: decoder))
        case "totp":
            self = .typeUpdateLoginFlowWithTotpMethod(try UpdateLoginFlowWithTotpMethod(from: decoder))
        case "webauthn":
            self = .typeUpdateLoginFlowWithWebAuthnMethod(try UpdateLoginFlowWithWebAuthnMethod(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UpdateLoginFlowBody"
                )
            )
        }
    }
}

