//
// UpdateLoginFlowWithSamlMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update login flow using SAML */
public struct UpdateLoginFlowWithSamlMethod: Sendable, Codable, Hashable {

    /** The CSRF Token */
    public var csrfToken: String?
    /** Method to use  This field must be set to `saml` when using the saml method. */
    public var method: String
    /** The provider to register with */
    public var provider: String
    /** Transient data to pass along to any webhooks */
    public var transientPayload: JSONValue?

    public init(csrfToken: String? = nil, method: String, provider: String, transientPayload: JSONValue? = nil) {
        self.csrfToken = csrfToken
        self.method = method
        self.provider = provider
        self.transientPayload = transientPayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case csrfToken = "csrf_token"
        case method
        case provider
        case transientPayload = "transient_payload"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(csrfToken, forKey: .csrfToken)
        try container.encode(method, forKey: .method)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(transientPayload, forKey: .transientPayload)
    }
}

