//
// UpdateRegistrationFlowWithPasswordMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Registration Flow with Password Method */
public struct UpdateRegistrationFlowWithPasswordMethod: Sendable, Codable, Hashable {

    /** The CSRF Token */
    public var csrfToken: String?
    /** Method to use  This field must be set to `password` when using the password method. */
    public var method: String
    /** Password to sign the user up with */
    public var password: String
    /** The identity's traits */
    public var traits: JSONValue
    /** Transient data to pass along to any webhooks */
    public var transientPayload: JSONValue?

    public init(csrfToken: String? = nil, method: String, password: String, traits: JSONValue, transientPayload: JSONValue? = nil) {
        self.csrfToken = csrfToken
        self.method = method
        self.password = password
        self.traits = traits
        self.transientPayload = transientPayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case csrfToken = "csrf_token"
        case method
        case password
        case traits
        case transientPayload = "transient_payload"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(csrfToken, forKey: .csrfToken)
        try container.encode(method, forKey: .method)
        try container.encode(password, forKey: .password)
        try container.encode(traits, forKey: .traits)
        try container.encodeIfPresent(transientPayload, forKey: .transientPayload)
    }
}

