//
// UpdateRecoveryFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Recovery Flow Request Body */
public enum UpdateRecoveryFlowBody: Sendable, Codable, Hashable {
    case typeUpdateRecoveryFlowWithCodeMethod(UpdateRecoveryFlowWithCodeMethod)
    case typeUpdateRecoveryFlowWithLinkMethod(UpdateRecoveryFlowWithLinkMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateRecoveryFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeUpdateRecoveryFlowWithLinkMethod(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case method = "method"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .method)

        switch discriminatorValue {
        case "code":
            self = .typeUpdateRecoveryFlowWithCodeMethod(try UpdateRecoveryFlowWithCodeMethod(from: decoder))
        case "link":
            self = .typeUpdateRecoveryFlowWithLinkMethod(try UpdateRecoveryFlowWithLinkMethod(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UpdateRecoveryFlowBody"
                )
            )
        }
    }
}

