//
// UpdateRegistrationFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Registration Request Body */
public enum UpdateRegistrationFlowBody: Sendable, Codable, Hashable {
    case typeUpdateRegistrationFlowWithCodeMethod(UpdateRegistrationFlowWithCodeMethod)
    case typeUpdateRegistrationFlowWithOidcMethod(UpdateRegistrationFlowWithOidcMethod)
    case typeUpdateRegistrationFlowWithPasskeyMethod(UpdateRegistrationFlowWithPasskeyMethod)
    case typeUpdateRegistrationFlowWithPasswordMethod(UpdateRegistrationFlowWithPasswordMethod)
    case typeUpdateRegistrationFlowWithProfileMethod(UpdateRegistrationFlowWithProfileMethod)
    case typeUpdateRegistrationFlowWithSamlMethod(UpdateRegistrationFlowWithSamlMethod)
    case typeUpdateRegistrationFlowWithWebAuthnMethod(UpdateRegistrationFlowWithWebAuthnMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateRegistrationFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeUpdateRegistrationFlowWithOidcMethod(let value):
            try container.encode(value)
        case .typeUpdateRegistrationFlowWithPasskeyMethod(let value):
            try container.encode(value)
        case .typeUpdateRegistrationFlowWithPasswordMethod(let value):
            try container.encode(value)
        case .typeUpdateRegistrationFlowWithProfileMethod(let value):
            try container.encode(value)
        case .typeUpdateRegistrationFlowWithSamlMethod(let value):
            try container.encode(value)
        case .typeUpdateRegistrationFlowWithWebAuthnMethod(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case method = "method"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .method)

        switch discriminatorValue {
        case "code":
            self = .typeUpdateRegistrationFlowWithCodeMethod(try UpdateRegistrationFlowWithCodeMethod(from: decoder))
        case "oidc":
            self = .typeUpdateRegistrationFlowWithOidcMethod(try UpdateRegistrationFlowWithOidcMethod(from: decoder))
        case "passkey":
            self = .typeUpdateRegistrationFlowWithPasskeyMethod(try UpdateRegistrationFlowWithPasskeyMethod(from: decoder))
        case "password":
            self = .typeUpdateRegistrationFlowWithPasswordMethod(try UpdateRegistrationFlowWithPasswordMethod(from: decoder))
        case "profile":
            self = .typeUpdateRegistrationFlowWithProfileMethod(try UpdateRegistrationFlowWithProfileMethod(from: decoder))
        case "saml":
            self = .typeUpdateRegistrationFlowWithSamlMethod(try UpdateRegistrationFlowWithSamlMethod(from: decoder))
        case "webauthn":
            self = .typeUpdateRegistrationFlowWithWebAuthnMethod(try UpdateRegistrationFlowWithWebAuthnMethod(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UpdateRegistrationFlowBody"
                )
            )
        }
    }
}

