//
// UpdateOrganizationOnboardingPortalLinkBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateOrganizationOnboardingPortalLinkBody: Sendable, Codable, Hashable {

    /** Feature flag to enable SCIM configuration */
    public var enableScim: Bool
    /** Feature flag to enable SSO configuration */
    public var enableSso: Bool
    public var expiresAt: Date?

    public init(enableScim: Bool, enableSso: Bool, expiresAt: Date? = nil) {
        self.enableScim = enableScim
        self.enableSso = enableSso
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enableScim = "enable_scim"
        case enableSso = "enable_sso"
        case expiresAt = "expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enableScim, forKey: .enableScim)
        try container.encode(enableSso, forKey: .enableSso)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}

