//
// VerifiableCredentialProof.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VerifiableCredentialProof: Sendable, Codable, Hashable {

    public var jwt: String?
    public var proofType: String?

    public init(jwt: String? = nil, proofType: String? = nil) {
        self.jwt = jwt
        self.proofType = proofType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jwt
        case proofType = "proof_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jwt, forKey: .jwt)
        try container.encodeIfPresent(proofType, forKey: .proofType)
    }
}

