//
// VerifyUserCodeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VerifyUserCodeRequest: Sendable, Codable, Hashable {

    public var client: OAuth2Client?
    public var deviceCodeRequestId: String?
    /** RequestURL is the original Device Authorization URL requested. */
    public var requestUrl: String?
    public var requestedAccessTokenAudience: [String]?
    public var requestedScope: [String]?

    public init(client: OAuth2Client? = nil, deviceCodeRequestId: String? = nil, requestUrl: String? = nil, requestedAccessTokenAudience: [String]? = nil, requestedScope: [String]? = nil) {
        self.client = client
        self.deviceCodeRequestId = deviceCodeRequestId
        self.requestUrl = requestUrl
        self.requestedAccessTokenAudience = requestedAccessTokenAudience
        self.requestedScope = requestedScope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case client
        case deviceCodeRequestId = "device_code_request_id"
        case requestUrl = "request_url"
        case requestedAccessTokenAudience = "requested_access_token_audience"
        case requestedScope = "requested_scope"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(client, forKey: .client)
        try container.encodeIfPresent(deviceCodeRequestId, forKey: .deviceCodeRequestId)
        try container.encodeIfPresent(requestUrl, forKey: .requestUrl)
        try container.encodeIfPresent(requestedAccessTokenAudience, forKey: .requestedAccessTokenAudience)
        try container.encodeIfPresent(requestedScope, forKey: .requestedScope)
    }
}

