//
// VerificationFlowState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The experimental state represents the state of a verification flow. This field is EXPERIMENTAL and subject to change! */
public enum VerificationFlowState: String, Sendable, Codable, CaseIterable {
    case chooseMethod = "choose_method"
    case sentEmail = "sent_email"
    case passedChallenge = "passed_challenge"
}
