//
// AcceptDeviceUserCodeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contains information on an device verification */
public struct AcceptDeviceUserCodeRequest: Sendable, Codable, Hashable {

    public var userCode: String?

    public init(userCode: String? = nil) {
        self.userCode = userCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userCode = "user_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userCode, forKey: .userCode)
    }
}

