//
// AttributeFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AttributeFilter: Sendable, Codable, Hashable {

    public enum Condition: String, Sendable, Codable, CaseIterable {
        case equals = "equals"
        case notEquals = "not_equals"
        case contains = "contains"
        case notContains = "not_contains"
        case regex = "regex"
        case notRegex = "not_regex"
        case _set = "set"
        case notSet = "not_set"
    }
    public var attribute: String?
    public var condition: Condition?
    public var value: String?

    public init(attribute: String? = nil, condition: Condition? = nil, value: String? = nil) {
        self.attribute = attribute
        self.condition = condition
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attribute
        case condition
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attribute, forKey: .attribute)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

