//
// CourierMessageStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A Message&#39;s Status */
public enum CourierMessageStatus: String, Sendable, Codable, CaseIterable {
    case queued = "queued"
    case sent = "sent"
    case processing = "processing"
    case abandoned = "abandoned"
}
