//
// CreateWorkspaceApiKeyBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateWorkspaceApiKeyBody: Sendable, Codable, Hashable {

    public var expiresAt: Date?
    /** The API Key Name  A descriptive name for the API key. */
    public var name: String

    public init(expiresAt: Date? = nil, name: String) {
        self.expiresAt = expiresAt
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt = "expires_at"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encode(name, forKey: .name)
    }
}

