//
// GenericUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GenericUsage: Sendable, Codable, Hashable {

    public var additionalPrice: Money
    /** IncludedUsage is the number of included items. */
    public var includedUsage: Int64

    public init(additionalPrice: Money, includedUsage: Int64) {
        self.additionalPrice = additionalPrice
        self.includedUsage = includedUsage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case additionalPrice = "additional_price"
        case includedUsage = "included_usage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(additionalPrice, forKey: .additionalPrice)
        try container.encode(includedUsage, forKey: .includedUsage)
    }
}

