//
// InviteTokenBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Invite Token Body */
public struct InviteTokenBody: Sendable, Codable, Hashable {

    /** Invite Token  The Invite Token.  format: uuid */
    public var inviteToken: String

    public init(inviteToken: String) {
        self.inviteToken = inviteToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inviteToken = "invite_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inviteToken, forKey: .inviteToken)
    }
}

