//
// KeysetPaginationResponseHeaders.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The &#x60;Link&#x60; HTTP header contains multiple links (&#x60;first&#x60;, &#x60;next&#x60;) formatted as: &#x60;&lt;https://{project-slug}.projects.oryapis.com/admin/sessions?page_size&#x3D;250&amp;page_token&#x3D;&gt;; rel&#x3D;\&quot;first\&quot;&#x60;  For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). */
public struct KeysetPaginationResponseHeaders: Sendable, Codable, Hashable {

    /** The Link HTTP Header  The `Link` header contains a comma-delimited list of links to the following pages:  first: The first page of results. next: The next page of results.  Pages are omitted if they do not exist. For example, if there is no next page, the `next` link is omitted. Examples:  </admin/sessions?page_size=250&page_token={last_item_uuid}; rel=\"first\",/admin/sessions?page_size=250&page_token=>; rel=\"next\" */
    public var link: String?

    public init(link: String? = nil) {
        self.link = link
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case link
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(link, forKey: .link)
    }
}

