//
// NormalizedProjectRevisionScimClient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** SCIMClient represents a SCIM client configuration to be used by an external identity provider. */
public struct NormalizedProjectRevisionScimClient: Sendable, Codable, Hashable {

    public enum State: String, Sendable, Codable, CaseIterable {
        case enabled = "enabled"
        case disabled = "disabled"
    }
    /** The secret that the client uses in the authorization header to authenticate itself. */
    public var authorizationHeaderSecret: String
    /** The unique ID of the SCIM server. */
    public var clientId: String
    /** The SCIM client's creation time */
    public var createdAt: Date?
    public var id: String?
    /** The SCIM server's label */
    public var label: String
    /** Mapper specifies the JSONNet code snippet which uses the SCIM provider's data to hydrate the identity's data. */
    public var mapperUrl: String
    /** OrganizationID is the organization ID for this SCIM server. */
    public var organizationId: String
    public var proxyScimServerUrl: String?
    /** State indicates the state of the SCIM server  Only servers with state `enabled` will be available for SCIM provisioning. enabled ThirdPartyProviderStateEnabled disabled ThirdPartyProviderStateDisabled */
    public var state: State?
    /** Last time the SCIM client was updated */
    public var updatedAt: Date?

    public init(authorizationHeaderSecret: String, clientId: String, createdAt: Date? = nil, id: String? = nil, label: String, mapperUrl: String, organizationId: String, proxyScimServerUrl: String? = nil, state: State? = nil, updatedAt: Date? = nil) {
        self.authorizationHeaderSecret = authorizationHeaderSecret
        self.clientId = clientId
        self.createdAt = createdAt
        self.id = id
        self.label = label
        self.mapperUrl = mapperUrl
        self.organizationId = organizationId
        self.proxyScimServerUrl = proxyScimServerUrl
        self.state = state
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authorizationHeaderSecret = "authorization_header_secret"
        case clientId = "client_id"
        case createdAt = "created_at"
        case id
        case label
        case mapperUrl = "mapper_url"
        case organizationId = "organization_id"
        case proxyScimServerUrl = "proxy_scim_server_url"
        case state
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(authorizationHeaderSecret, forKey: .authorizationHeaderSecret)
        try container.encode(clientId, forKey: .clientId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(mapperUrl, forKey: .mapperUrl)
        try container.encode(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(proxyScimServerUrl, forKey: .proxyScimServerUrl)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension NormalizedProjectRevisionScimClient: Identifiable {}
