//
// UpdateSettingsFlowWithSamlMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update settings flow using SAML */
public struct UpdateSettingsFlowWithSamlMethod: Sendable, Codable, Hashable {

    /** The CSRF Token */
    public var csrfToken: String?
    /** Flow ID is the flow's ID.  in: query */
    public var flow: String?
    /** Link this provider  Either this or `unlink` must be set.  type: string in: body */
    public var link: String?
    /** Method  Should be set to saml when trying to update a profile. */
    public var method: String
    /** The identity's traits  in: body */
    public var traits: JSONValue?
    /** Transient data to pass along to any webhooks */
    public var transientPayload: JSONValue?
    /** Unlink this provider  Either this or `link` must be set.  type: string in: body */
    public var unlink: String?

    public init(csrfToken: String? = nil, flow: String? = nil, link: String? = nil, method: String, traits: JSONValue? = nil, transientPayload: JSONValue? = nil, unlink: String? = nil) {
        self.csrfToken = csrfToken
        self.flow = flow
        self.link = link
        self.method = method
        self.traits = traits
        self.transientPayload = transientPayload
        self.unlink = unlink
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case csrfToken = "csrf_token"
        case flow
        case link
        case method
        case traits
        case transientPayload = "transient_payload"
        case unlink
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(csrfToken, forKey: .csrfToken)
        try container.encodeIfPresent(flow, forKey: .flow)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encode(method, forKey: .method)
        try container.encodeIfPresent(traits, forKey: .traits)
        try container.encodeIfPresent(transientPayload, forKey: .transientPayload)
        try container.encodeIfPresent(unlink, forKey: .unlink)
    }
}

