//
// UpdateVerificationFlowBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update Verification Flow Request Body */
public enum UpdateVerificationFlowBody: Sendable, Codable, Hashable {
    case typeUpdateVerificationFlowWithCodeMethod(UpdateVerificationFlowWithCodeMethod)
    case typeUpdateVerificationFlowWithLinkMethod(UpdateVerificationFlowWithLinkMethod)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUpdateVerificationFlowWithCodeMethod(let value):
            try container.encode(value)
        case .typeUpdateVerificationFlowWithLinkMethod(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case method = "method"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .method)

        switch discriminatorValue {
        case "code":
            self = .typeUpdateVerificationFlowWithCodeMethod(try UpdateVerificationFlowWithCodeMethod(from: decoder))
        case "link":
            self = .typeUpdateVerificationFlowWithLinkMethod(try UpdateVerificationFlowWithLinkMethod(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for UpdateVerificationFlowBody"
                )
            )
        }
    }
}

