//
// WorkspaceApiKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WorkspaceApiKey: Sendable, Codable, Hashable {

    /** The API key's creation date */
    public var createdAt: Date?
    public var expiresAt: Date?
    /** The key's ID. */
    public var id: String
    /** The API key's Name  Set this to help you remember, for example, where you use the API key. */
    public var name: String
    /** The key's owner */
    public var ownerId: String
    /** The API key's last update date */
    public var updatedAt: Date?
    /** The key's value */
    public var value: String?
    /** The API key's workspace ID */
    public var workspaceId: String?

    public init(createdAt: Date? = nil, expiresAt: Date? = nil, id: String, name: String, ownerId: String, updatedAt: Date? = nil, value: String? = nil, workspaceId: String? = nil) {
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.id = id
        self.name = name
        self.ownerId = ownerId
        self.updatedAt = updatedAt
        self.value = value
        self.workspaceId = workspaceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case expiresAt = "expires_at"
        case id
        case name
        case ownerId = "owner_id"
        case updatedAt = "updated_at"
        case value
        case workspaceId = "workspace_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(ownerId, forKey: .ownerId)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
    }
}


extension WorkspaceApiKey: Identifiable {}
