//
// Workspace.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Workspace: Sendable, Codable, Hashable {

    public var createdAt: Date
    public var id: String
    public var name: String
    public var subscriptionId: String?
    public var subscriptionPlan: String?
    public var updatedAt: Date

    public init(createdAt: Date, id: String, name: String, subscriptionId: String? = nil, subscriptionPlan: String? = nil, updatedAt: Date) {
        self.createdAt = createdAt
        self.id = id
        self.name = name
        self.subscriptionId = subscriptionId
        self.subscriptionPlan = subscriptionPlan
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case id
        case name
        case subscriptionId = "subscription_id"
        case subscriptionPlan = "subscription_plan"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(subscriptionId, forKey: .subscriptionId)
        try container.encodeIfPresent(subscriptionPlan, forKey: .subscriptionPlan)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


extension Workspace: Identifiable {}
