//
// CourierAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CourierAPI {

    /**
     Get a Message
     
     - parameter id: (path) MessageID is the ID of the message. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Message
     */
    open class func getCourierMessage(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Message {
        return try await getCourierMessageWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a Message
     - GET /admin/courier/messages/{id}
     - Gets a specific messages by the given ID.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter id: (path) MessageID is the ID of the message. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Message> 
     */
    open class func getCourierMessageWithRequestBuilder(id: String, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Message> {
        var localVariablePath = "/admin/courier/messages/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Message>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List Messages
     
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter status: (query) Status filters out messages based on status. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter recipient: (query) Recipient filters out messages based on recipient. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Message]
     */
    open class func listCourierMessages(pageSize: Int64? = nil, pageToken: String? = nil, status: CourierMessageStatus? = nil, recipient: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> [Message] {
        return try await listCourierMessagesWithRequestBuilder(pageSize: pageSize, pageToken: pageToken, status: status, recipient: recipient, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List Messages
     - GET /admin/courier/messages
     - Lists all messages by given status and recipient.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter status: (query) Status filters out messages based on status. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter recipient: (query) Recipient filters out messages based on recipient. If no value is provided, it doesn&#39;t take effect on filter. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Message]> 
     */
    open class func listCourierMessagesWithRequestBuilder(pageSize: Int64? = nil, pageToken: String? = nil, status: CourierMessageStatus? = nil, recipient: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<[Message]> {
        let localVariablePath = "/admin/courier/messages"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_token": (wrappedValue: pageToken?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "recipient": (wrappedValue: recipient?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Message]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
