//
// MetadataAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MetadataAPI {

    /**
     Return Running Software Version.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetVersion200Response
     */
    open class func getVersion(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetVersion200Response {
        return try await getVersionWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Return Running Software Version.
     - GET /version
     - This endpoint returns the version of Ory Kratos.  If the service supports TLS Edge Termination, this endpoint does not require the `X-Forwarded-Proto` header to be set.  Be aware that if you are running multiple nodes of this service, the version will never refer to the cluster state, only to a single instance.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetVersion200Response> 
     */
    open class func getVersionWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<GetVersion200Response> {
        let localVariablePath = "/version"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetVersion200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
