//
// RelationshipAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RelationshipAPI {

    /**
     Check the syntax of an OPL file
     
     - parameter body: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CheckOplSyntaxResult
     */
    open class func checkOplSyntax(body: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> CheckOplSyntaxResult {
        return try await checkOplSyntaxWithRequestBuilder(body: body, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check the syntax of an OPL file
     - POST /opl/syntax/check
     - The OPL file is expected in the body of the request.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter body: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CheckOplSyntaxResult> 
     */
    open class func checkOplSyntaxWithRequestBuilder(body: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<CheckOplSyntaxResult> {
        let localVariablePath = "/opl/syntax/check"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "text/plain",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckOplSyntaxResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a Relationship
     
     - parameter createRelationshipBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Relationship
     */
    open class func createRelationship(createRelationshipBody: CreateRelationshipBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Relationship {
        return try await createRelationshipWithRequestBuilder(createRelationshipBody: createRelationshipBody, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a Relationship
     - PUT /admin/relation-tuples
     - Use this endpoint to create a relationship.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter createRelationshipBody: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Relationship> 
     */
    open class func createRelationshipWithRequestBuilder(createRelationshipBody: CreateRelationshipBody? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Relationship> {
        let localVariablePath = "/admin/relation-tuples"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createRelationshipBody, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Relationship>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete Relationships
     
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteRelationships(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteRelationshipsWithRequestBuilder(namespace: namespace, object: object, relation: relation, subjectId: subjectId, subjectSetNamespace: subjectSetNamespace, subjectSetObject: subjectSetObject, subjectSetRelation: subjectSetRelation, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete Relationships
     - DELETE /admin/relation-tuples
     - Use this endpoint to delete relationships
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteRelationshipsWithRequestBuilder(namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/admin/relation-tuples"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "namespace": (wrappedValue: namespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "object": (wrappedValue: object?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "relation": (wrappedValue: relation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_id": (wrappedValue: subjectId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.namespace": (wrappedValue: subjectSetNamespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.object": (wrappedValue: subjectSetObject?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.relation": (wrappedValue: subjectSetRelation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Query relationships
     
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Relationships
     */
    open class func getRelationships(pageSize: Int64? = nil, pageToken: String? = nil, namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> Relationships {
        return try await getRelationshipsWithRequestBuilder(pageSize: pageSize, pageToken: pageToken, namespace: namespace, object: object, relation: relation, subjectId: subjectId, subjectSetNamespace: subjectSetNamespace, subjectSetObject: subjectSetObject, subjectSetRelation: subjectSetRelation, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Query relationships
     - GET /relation-tuples
     - Get all relationships that match the query. Only the namespace field is required.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter pageSize: (query) Items per Page  This is the number of items per page to return. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional, default to 250)
     - parameter pageToken: (query) Next Page Token  The next page token. For details on pagination please head over to the [pagination documentation](https://www.ory.sh/docs/ecosystem/api-design#pagination). (optional)
     - parameter namespace: (query) Namespace of the Relationship (optional)
     - parameter object: (query) Object of the Relationship (optional)
     - parameter relation: (query) Relation of the Relationship (optional)
     - parameter subjectId: (query) SubjectID of the Relationship (optional)
     - parameter subjectSetNamespace: (query) Namespace of the Subject Set (optional)
     - parameter subjectSetObject: (query) Object of the Subject Set (optional)
     - parameter subjectSetRelation: (query) Relation of the Subject Set (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Relationships> 
     */
    open class func getRelationshipsWithRequestBuilder(pageSize: Int64? = nil, pageToken: String? = nil, namespace: String? = nil, object: String? = nil, relation: String? = nil, subjectId: String? = nil, subjectSetNamespace: String? = nil, subjectSetObject: String? = nil, subjectSetRelation: String? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Relationships> {
        let localVariablePath = "/relation-tuples"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_token": (wrappedValue: pageToken?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "namespace": (wrappedValue: namespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "object": (wrappedValue: object?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "relation": (wrappedValue: relation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_id": (wrappedValue: subjectId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.namespace": (wrappedValue: subjectSetNamespace?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.object": (wrappedValue: subjectSetObject?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "subject_set.relation": (wrappedValue: subjectSetRelation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Relationships>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Query namespaces
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RelationshipNamespaces
     */
    open class func listRelationshipNamespaces(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) -> RelationshipNamespaces {
        return try await listRelationshipNamespacesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Query namespaces
     - GET /namespaces
     - Get all namespaces
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RelationshipNamespaces> 
     */
    open class func listRelationshipNamespacesWithRequestBuilder(apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<RelationshipNamespaces> {
        let localVariablePath = "/namespaces"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RelationshipNamespaces>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Patch Multiple Relationships
     
     - parameter relationshipPatch: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func patchRelationships(relationshipPatch: [RelationshipPatch]? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await patchRelationshipsWithRequestBuilder(relationshipPatch: relationshipPatch, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Patch Multiple Relationships
     - PATCH /admin/relation-tuples
     - Use this endpoint to patch one or more relationships.
     - Bearer Token:
       - type: http
       - name: oryAccessToken
     - parameter relationshipPatch: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func patchRelationshipsWithRequestBuilder(relationshipPatch: [RelationshipPatch]? = nil, apiConfiguration: OryClientAPIConfiguration = OryClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/admin/relation-tuples"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: relationshipPatch, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
